// frontend/src/app/dashboard/journal/new/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import TextareaAutosize from 'react-textarea-autosize'
import { 
  BookOpen, 
  Save, 
  ArrowLeft, 
  Sparkles, 
  FlaskConical,
  MessageCircle 
} from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { Experiment } from '@/types'
import { LoadingSpinner } from '@/components/LoadingSpinner'
import { ErrorMessage } from '@/components/ErrorMessage'

const journalEntrySchema = z.object({
  content: z.string()
    .min(10, 'Please write at least 10 characters')
    .max(10000, 'Entry is too long (max 10,000 characters)'),
  experimentId: z.string().optional(),
})

type JournalEntryFormData = z.infer<typeof journalEntrySchema>

export default function NewJournalEntryPage() {
  const [isLoading, setIsLoading] = useState(false)
  const [isCreating, setIsCreating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [experiments, setExperiments] = useState<Experiment[]>([])
  const [showExperimentSelector, setShowExperimentSelector] = useState(false)
  const router = useRouter()

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors },
  } = useForm<JournalEntryFormData>({
    resolver: zodResolver(journalEntrySchema),
    defaultValues: {
      content: '',
      experimentId: '',
    }
  })

  const content = watch('content')
  const selectedExperimentId = watch('experimentId')

  // Load experiments on mount
  useEffect(() => {
    const loadExperiments = async () => {
      try {
        setIsLoading(true)
        const response = await apiClient.getExperiments()
        if (response.success && response.data) {
          // Filter for active experiments
          const now = new Date()
          const activeExperiments = response.data.filter(exp => {
            const startDate = new Date(exp.startDate)
            const endDate = new Date(exp.endDate)
            return now >= startDate && now <= endDate
          })
          setExperiments(activeExperiments)
        }
      } catch (err) {
        console.error('Error loading experiments:', err)
      } finally {
        setIsLoading(false)
      }
    }

    loadExperiments()
  }, [])

  const onSubmit = async (data: JournalEntryFormData) => {
    setIsCreating(true)
    setError(null)

    try {
      const response = await apiClient.createJournalEntry({
        content: data.content,
        experimentId: data.experimentId || undefined,
      })

      if (response.success && response.data) {
        // Redirect to the created entry
        router.push(`/dashboard/journal/${response.data.id}`)
      } else {
        setError(response.error || 'Failed to create journal entry')
      }
    } catch (err) {
      console.error('Error creating journal entry:', err)
      setError('Unable to create journal entry. Please try again.')
    } finally {
      setIsCreating(false)
    }
  }

  const selectedExperiment = experiments.find(exp => exp.id === selectedExperimentId)
  const wordCount = content ? content.trim().split(/\s+/).filter(word => word.length > 0).length : 0

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <Link 
            href="/dashboard/journal" 
            className="btn btn-ghost btn-circle"
            aria-label="Back to journal"
          >
            <ArrowLeft className="h-5 w-5" />
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-base-content flex items-center gap-2">
              <BookOpen className="h-6 w-6 text-journal-primary" />
              New Journal Entry
            </h1>
            <p className="text-base-content/60">Share your thoughts and reflections</p>
          </div>
        </div>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        <div className="card bg-base-100 shadow-lg">
          <div className="card-body">
            {/* Experiment Selection */}
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <FlaskConical className="h-4 w-4 text-experiment-active" />
                <span className="text-sm font-medium">Link to Experiment</span>
              </div>
              <button
                type="button"
                onClick={() => setShowExperimentSelector(!showExperimentSelector)}
                className="btn btn-sm btn-ghost"
              >
                {selectedExperiment ? 'Change' : 'Select'}
              </button>
            </div>

            {showExperimentSelector && (
              <div className="mb-4 p-4 bg-base-50 rounded-lg">
                <div className="form-control">
                  <label className="label">
                    <span className="label-text">Choose an active experiment (optional)</span>
                  </label>
                  <select
                    {...register('experimentId')}
                    className="select select-bordered"
                    disabled={isLoading}
                  >
                    <option value="">No experiment</option>
                    {experiments.map((experiment) => (
                      <option key={experiment.id} value={experiment.id}>
                        {experiment.title}
                      </option>
                    ))}
                  </select>
                </div>
                <button
                  type="button"
                  onClick={() => setShowExperimentSelector(false)}
                  className="btn btn-sm btn-ghost mt-2"
                >
                  Done
                </button>
              </div>
            )}

            {selectedExperiment && (
              <div className="alert alert-info mb-4">
                <FlaskConical className="h-4 w-4" />
                <div>
                  <div className="font-medium">Linked to: {selectedExperiment.title}</div>
                  <div className="text-xs opacity-70">{selectedExperiment.description}</div>
                </div>
                <button
                  type="button"
                  onClick={() => setValue('experimentId', '')}
                  className="btn btn-sm btn-ghost"
                >
                  Remove
                </button>
              </div>
            )}

            {/* Main Content Area */}
            <div className="form-control">
              <label className="label">
                <span className="label-text">What's on your mind?</span>
                <span className="label-text-alt text-base-content/60">
                  {wordCount} words
                </span>
              </label>
              <TextareaAutosize
                {...register('content')}
                placeholder="Start writing about your day, thoughts, or experiences. The AI will ask follow-up questions to help you reflect deeper..."
                className={`textarea textarea-bordered w-full resize-none ${
                  errors.content ? 'textarea-error' : 'focus:textarea-primary'
                }`}
                minRows={8}
                maxRows={20}
                disabled={isCreating}
              />
              {errors.content && (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.content.message}</span>
                </label>
              )}
            </div>

            {/* Writing Tips */}
            <div className="bg-base-50 rounded-lg p-4 mt-4">
              <div className="flex items-start space-x-2">
                <Sparkles className="h-4 w-4 text-journal-primary mt-0.5 flex-shrink-0" />
                <div className="text-sm">
                  <div className="font-medium text-base-content mb-1">Writing Tips:</div>
                  <ul className="text-base-content/70 space-y-1 text-xs">
                    <li>• Write about specific events, feelings, or observations from your day</li>
                    <li>• Don't worry about perfect grammar - focus on authentic expression</li>
                    <li>• The AI will ask follow-up questions to help you dig deeper</li>
                    <li>• Mention any experiments you're running to track their impact</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <ErrorMessage 
            message={error} 
            onRetry={() => setError(null)}
          />
        )}

        {/* Actions */}
        <div className="flex items-center justify-between">
          <Link href="/dashboard/journal" className="btn btn-ghost">
            Cancel
          </Link>
          
          <div className="flex items-center space-x-3">
            <div className="text-sm text-base-content/60">
              {content.length > 0 && (
                <span>Ready to start the conversation</span>
              )}
            </div>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={isCreating || !content.trim()}
            >
              {isCreating ? (
                <LoadingSpinner size="sm" />
              ) : (
                <>
                  <MessageCircle className="h-4 w-4 mr-2" />
                  Start Conversation
                </>
              )}
            </button>
          </div>
        </div>
      </form>
    </div>
  )
}

// src/routes/tasks/new/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { ListChecks, ArrowLeft, Plus, Trash, InfoCircle } from 'lucide-svelte';
	import type { Experiment } from '$lib/types';
	import type { CharacterStat } from '$lib/types';
	
	let title = $state('');
	let description = $state('');
	let selectedExperimentId = $state('');
	let targetCompletions = $state(1);
	let experiments = $state<Experiment[]>([]);
	let stats = $state<CharacterStat[]>([]);
	let statRewards = $state<{statId: string, xp: number}[]>([]);
	let loading = $state(false);
	let loadingData = $state(true);
	let error = $state('');
	let success = $state('');
	
	onMount(async () => {
		await Promise.all([loadExperiments(), loadStats()]);
		loadingData = false;
	});
	
	async function loadExperiments() {
		try {
			const response = await fetch('/api/experiments');
			
			if (response.ok) {
				const data = await response.json();
				experiments = data.experiments || [];
				
				// Auto-select first experiment if available
				if (experiments.length > 0 && !selectedExperimentId) {
					selectedExperimentId = experiments[0].id;
				}
			}
		} catch (err) {
			console.error('Error loading experiments:', err);
		}
	}
	
	async function loadStats() {
		try {
			const response = await fetch('/api/stats');
			
			if (response.ok) {
				const data = await response.json();
				stats = data.stats || [];
			}
		} catch (err) {
			console.error('Error loading stats:', err);
		}
	}
	
	function addStatReward() {
		if (stats.length > 0) {
			const availableStats = stats.filter(stat => 
				!statRewards.some(reward => reward.statId === stat.id)
			);
			
			if (availableStats.length > 0) {
				statRewards = [...statRewards, {
					statId: availableStats[0].id,
					xp: 5
				}];
			}
		}
	}
	
	function removeStatReward(index: number) {
		statRewards = statRewards.filter((_, i) => i !== index);
	}
	
	function getStatName(statId: string) {
		return stats.find(s => s.id === statId)?.name || 'Unknown';
	}
	
	async function saveTask() {
		if (!title.trim()) {
			error = 'Task title is required';
			return;
		}
		
		if (!selectedExperimentId) {
			error = 'Please select an experiment';
			return;
		}
		
		loading = true;
		error = '';
		success = '';
		
		try {
			// Convert statRewards array to object format
			const xpRewards = statRewards.reduce((obj, reward) => {
				obj[reward.statId] = reward.xp;
				return obj;
			}, {} as Record<string, number>);
			
			const response = await fetch('/api/tasks', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					experimentId: selectedExperimentId,
					title,
					description,
					targetCompletions,
					xpRewards
				})
			});
			
			if (response.ok) {
				const data = await response.json();
				success = 'Task created successfully!';
				setTimeout(() => {
					goto('/tasks');
				}, 1000);
			} else {
				const errorData = await response.json();
				error = errorData.error || 'Failed to create task';
			}
		} catch (err) {
			console.error('Error creating task:', err);
			error = 'An error occurred while creating the task';
		} finally {
			loading = false;
		}
	}
</script>

<svelte:head>
	<title>Create Task - Journal App</title>
</svelte:head>

<div class="max-w-2xl mx-auto space-y-6">
	<!-- Header -->
	<div>
		<div class="flex items-center gap-3">
			<a href="/tasks" class="btn btn-ghost btn-sm">
				<ArrowLeft size={16} />
				Back to Tasks
			</a>
		</div>
		<h1 class="text-2xl font-bold mt-2">Create New Task</h1>
	</div>

	{#if loadingData}
		<div class="flex justify-center py-12">
			<span class="loading loading-spinner loading-lg"></span>
		</div>
	{:else}
		{#if experiments.length === 0}
			<div class="alert alert-warning">
				<span>You need to create an experiment before you can add tasks</span>
				<a href="/experiments/new" class="btn btn-sm">Create Experiment</a>
			</div>
		{:else}
			<!-- Task Form -->
			<div class="card bg-base-100 border border-base-300">
				<div class="card-body">
					{#if error}
						<div class="alert alert-error mb-4">
							<span>{error}</span>
						</div>
					{/if}
					
					{#if success}
						<div class="alert alert-success mb-4">
							<span>{success}</span>
						</div>
					{/if}
					
					<form on:submit|preventDefault={saveTask} class="space-y-4">
						<!-- Experiment Selection -->
						<div class="form-control">
							<label for="experiment" class="label">
								<span class="label-text">Experiment</span>
							</label>
							<select 
								id="experiment" 
								class="select select-bordered w-full" 
								bind:value={selectedExperimentId}
								required
							>
								<option value="" disabled>Select an experiment</option>
								{#each experiments as experiment}
									<option value={experiment.id}>{experiment.title}</option>
								{/each}
							</select>
						</div>
						
						<!-- Task Title -->
						<div class="form-control">
							<label for="title" class="label">
								<span class="label-text">Task Title</span>
							</label>
							<input 
								type="text" 
								id="title" 
								class="input input-bordered w-full" 
								placeholder="Enter task title" 
								bind:value={title}
								required
							/>
						</div>
						
						<!-- Task Description -->
						<div class="form-control">
							<label for="description" class="label">
								<span class="label-text">Description (Optional)</span>
							</label>
							<textarea 
								id="description" 
								class="textarea textarea-bordered h-24" 
								placeholder="Enter task description" 
								bind:value={description}
							></textarea>
						</div>
						
						<!-- Target Completions -->
						<div class="form-control">
							<label for="completions" class="label">
								<span class="label-text">Target Completions</span>
								<span class="label-text-alt flex items-center gap-1">
									<InfoCircle size={14} />
									How many times this task should be completed
								</span>
							</label>
							<input 
								type="number" 
								id="completions" 
								class="input input-bordered w-full" 
								min="1" 
								max="100" 
								bind:value={targetCompletions}
							/>
						</div>
						
						<!-- XP Rewards -->
						<div class="form-control">
							<label class="label">
								<span class="label-text">XP Rewards (Optional)</span>
							</label>
							
							{#if statRewards.length > 0}
								<div class="space-y-3 mb-3">
									{#each statRewards as reward, index}
										<div class="flex items-center gap-2">
											<div class="flex-1">
												<select 
													class="select select-bordered select-sm w-full" 
													bind:value={reward.statId}
												>
													{#each stats as stat}
														<option value={stat.id} disabled={statRewards.some((r, i) => i !== index && r.statId === stat.id)}>
															{stat.name}
														</option>
													{/each}
												</select>
											</div>
											<div class="flex-none w-24">
												<input 
													type="number" 
													class="input input-bordered input-sm w-full" 
													min="1" 
													max="100" 
													bind:value={reward.xp}
												/>
											</div>
											<button 
												type="button"
												class="btn btn-sm btn-error btn-square"
												on:click={() => removeStatReward(index)}
											>
												<Trash size={16} />
											</button>
										</div>
									{/each}
								</div>
							{/if}
							
							<button 
								type="button" 
								class="btn btn-sm btn-outline" 
								on:click={addStatReward}
								disabled={statRewards.length >= stats.length}
							>
								<Plus size={16} />
								Add XP Reward
							</button>
						</div>
						
						<!-- Submit Button -->
						<div class="mt-6">
							<button 
								type="submit" 
								class="btn btn-primary w-full"
								disabled={loading || !title || !selectedExperimentId}
							>
								{#if loading}
									<span class="loading loading-spinner loading-sm"></span>
								{:else}
									<ListChecks size={18} />
								{/if}
								Create Task
							</button>
						</div>
					</form>
				</div>
			</div>
		{/if}
	{/if}
</div>
