// frontend/app/register/page.tsx
"use client"

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { BookOpen, UserPlus, Mail, Lock, Loader2, ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import { useAuth } from '@/lib/auth-context'

export default function RegisterPage() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [passwordError, setPasswordError] = useState('')
  const { register, isLoading, error } = useAuth()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!email || !password || !confirmPassword) return
    
    if (password !== confirmPassword) {
      setPasswordError("Passwords don't match")
      return
    }
    
    setPasswordError('')
    await register(email, password)
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-50 to-blue-50 px-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <div className="flex justify-center mb-3">
            <BookOpen className="h-10 w-10 text-emerald-500" />
          </div>
          <h1 className="text-2xl font-bold text-slate-800">Journal App</h1>
          <p className="text-slate-600">Create your account</p>
        </div>

        <Card className="border-slate-200 shadow-md">
          <CardHeader>
            <CardTitle className="text-xl">Register</CardTitle>
            <CardDescription>
              Create a new account to start journaling
            </CardDescription>
          </CardHeader>
          
          <form onSubmit={handleSubmit}>
            <CardContent className="space-y-4">
              {error && (
                <div className="p-3 bg-red-50 border border-red-200 text-red-600 text-sm rounded">
                  {error}
                </div>
              )}
              
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-400 h-4 w-4" />
                  <Input
                    id="email"
                    type="email"
                    placeholder="name@example.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="pl-10"
                    required
                    disabled={isLoading}
                  />
                </div>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-400 h-4 w-4" />
                  <Input
                    id="password"
                    type="password"
                    placeholder="••••••••"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    className="pl-10"
                    required
                    disabled={isLoading}
                  />
                </div>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="confirmPassword">Confirm Password</Label>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-400 h-4 w-4" />
                  <Input
                    id="confirmPassword"
                    type="password"
                    placeholder="••••••••"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    className={`pl-10 ${passwordError ? 'border-red-500' : ''}`}
                    required
                    disabled={isLoading}
                  />
                </div>
                {passwordError && (
                  <p className="text-red-500 text-xs mt-1">{passwordError}</p>
                )}
              </div>
            </CardContent>
            
            <CardFooter className="flex flex-col space-y-4">
              <Button 
                type="submit" 
                className="w-full bg-emerald-500 hover:bg-emerald-600"
                disabled={isLoading || !email || !password || !confirmPassword}
              >
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Creating Account...
                  </>
                ) : (
                  <>
                    <UserPlus className="mr-2 h-4 w-4" />
                    Sign Up
                  </>
                )}
              </Button>
              
              <div className="text-center text-sm text-slate-600">
                Already have an account?{' '}
                <Link href="/login" className="text-emerald-600 hover:text-emerald-700 font-medium">
                  Sign in
                </Link>
              </div>
            </CardFooter>
          </form>
        </Card>
      </div>
    </div>
  )
}

// src/routes/auth/register/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { User, Mail, Lock } from 'lucide-svelte';
	
	let username = $state('');
	let email = $state('');
	let password = $state('');
	let confirmPassword = $state('');
	let error = $state('');
	let submitting = $state(false);
	
	async function handleRegister() {
		try {
			submitting = true;
			error = '';
			
			// Validate passwords match
			if (password !== confirmPassword) {
				error = 'Passwords do not match';
				submitting = false;
				return;
			}
			
			const response = await fetch('/api/auth/register', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					username,
					email,
					password
				})
			});
			
			const data = await response.json();
			
			if (!response.ok) {
				error = data.error || 'Failed to create account';
				return;
			}
			
			// Redirect to login on successful registration
			goto('/auth/login');
		} catch (err) {
			console.error('Registration error:', err);
			error = 'An unexpected error occurred';
		} finally {
			submitting = false;
		}
	}
</script>

<svelte:head>
	<title>Register - Journal App</title>
</svelte:head>

<div class="min-h-screen flex flex-col items-center justify-center p-4 bg-base-200">
	<div class="w-full max-w-md p-6 bg-base-100 rounded-lg shadow-lg border border-base-300">
		<div class="text-center mb-6">
			<h1 class="text-3xl font-bold text-base-content">Create Account</h1>
			<p class="text-base-content/70 mt-1">Start your personal journey today</p>
		</div>
		
		{#if error}
			<div class="alert alert-error mb-4">
				<span>{error}</span>
			</div>
		{/if}
		
		<form onsubmit={(e) => { e.preventDefault(); handleRegister(); }} class="space-y-4">
			<div class="form-control">
				<label for="username" class="label">
					<span class="label-text">Username</span>
				</label>
				<div class="relative">
					<div class="absolute left-3 top-1/2 transform -translate-y-1/2 opacity-70">
						<User size={18} />
					</div>
					<input 
						type="text" 
						id="username"
						class="input input-bordered w-full pl-10" 
						placeholder="username"
						bind:value={username}
						required
					/>
				</div>
			</div>
			
			<div class="form-control">
				<label for="email" class="label">
					<span class="label-text">Email</span>
				</label>
				<div class="relative">
					<div class="absolute left-3 top-1/2 transform -translate-y-1/2 opacity-70">
						<Mail size={18} />
					</div>
					<input 
						type="email" 
						id="email"
						class="input input-bordered w-full pl-10" 
						placeholder="your@email.com"
						bind:value={email}
						required
					/>
				</div>
			</div>
			
			<div class="form-control">
				<label for="password" class="label">
					<span class="label-text">Password</span>
				</label>
				<div class="relative">
					<div class="absolute left-3 top-1/2 transform -translate-y-1/2 opacity-70">
						<Lock size={18} />
					</div>
					<input 
						type="password" 
						id="password"
						class="input input-bordered w-full pl-10" 
						placeholder="Password (min 8 characters)"
						minlength="8"
						bind:value={password}
						required
					/>
				</div>
			</div>
			
			<div class="form-control">
				<label for="confirm-password" class="label">
					<span class="label-text">Confirm Password</span>
				</label>
				<div class="relative">
					<div class="absolute left-3 top-1/2 transform -translate-y-1/2 opacity-70">
						<Lock size={18} />
					</div>
					<input 
						type="password" 
						id="confirm-password"
						class="input input-bordered w-full pl-10" 
						placeholder="Confirm your password"
						bind:value={confirmPassword}
						required
					/>
				</div>
			</div>
			
			<div class="form-control mt-6">
				<button 
					type="submit" 
					class="btn btn-primary w-full" 
					disabled={submitting}
				>
					{#if submitting}
						<span class="loading loading-spinner loading-sm"></span>
						Creating Account...
					{:else}
						Register
					{/if}
				</button>
			</div>
			
			<div class="text-center text-sm mt-4">
				Already have an account? 
				<a href="/auth/login" class="text-primary hover:underline">Login</a>
			</div>
		</form>
	</div>
</div>
