// src/app/register/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { signIn } from 'next-auth/react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  Container,
  Box,
  Avatar,
  Typography,
  TextField,
  Button,
  Grid,
  Alert,
  Paper,
} from '@mui/material';
import { PersonAdd as PersonAddIcon } from '@mui/icons-material';

const registerSchema = z
  .object({
    name: z.string().min(1, { message: 'Name is required' }),
    email: z.string().email({ message: 'Please enter a valid email address' }),
    password: z.string().min(8, { message: 'Password must be at least 8 characters' }),
    confirmPassword: z.string().min(1, { message: 'Please confirm your password' }),
  })
  .refine((data) => data.password === data.confirmPassword, {
    path: ['confirmPassword'],
    message: 'Passwords do not match',
  });

type RegisterFormValues = z.infer<typeof registerSchema>;

export default function RegisterPage() {
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterFormValues>({
    resolver: zodResolver(registerSchema),
  });

  const onSubmit = async (data: RegisterFormValues) => {
    setIsSubmitting(true);
    setError(null);

    const { name, email, password } = data;

    try {
      // Step 1: Register the user
      const registerResponse = await fetch('/api/register', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ name, email, password }),
      });

      const registerData = await registerResponse.json();
      
      if (!registerResponse.ok) {
        setError(registerData.error || 'Registration failed. Please try again.');
        setIsSubmitting(false);
        return;
      }

      // Step 2: Sign in the user
      const signInResult = await signIn('credentials', {
        redirect: false,
        email,
        password,
      });

      if (!signInResult?.ok) {
        setError('Registration successful, but automatic login failed. Please try logging in.');
        setIsSubmitting(false);
        router.push('/login');
        return;
      }

      // Success - redirect to home page
      router.push('/');
      router.refresh();
    } catch (err) {
      console.error('Registration error:', err);
      setError('An error occurred. Please try again.');
      setIsSubmitting(false);
    }
  };

  return (
    <Container maxWidth="xs">
      <Box
        sx={{
          marginTop: 8,
          marginBottom: 8,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        }}
      >
        <Paper
          elevation={3}
          sx={{
            p: 4,
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            width: '100%',
          }}
        >
          <Avatar sx={{ m: 1, bgcolor: 'primary.main' }}>
            <PersonAddIcon />
          </Avatar>
          <Typography component="h1" variant="h5" sx={{ mb: 3 }}>
            Create an account
          </Typography>
          
          {error && (
            <Alert severity="error" sx={{ width: '100%', mb: 2 }}>
              {error}
            </Alert>
          )}

          <Box
            component="form"
            noValidate
            onSubmit={handleSubmit(onSubmit)}
            sx={{ mt: 1, width: '100%' }}
          >
            <TextField
              margin="normal"
              required
              fullWidth
              id="name"
              label="Full Name"
              autoComplete="name"
              autoFocus
              {...register('name')}
              error={!!errors.name}
              helperText={errors.name?.message}
            />
            <TextField
              margin="normal"
              required
              fullWidth
              id="email"
              label="Email Address"
              autoComplete="email"
              {...register('email')}
              error={!!errors.email}
              helperText={errors.email?.message}
            />
            <TextField
              margin="normal"
              required
              fullWidth
              label="Password"
              type="password"
              id="password"
              autoComplete="new-password"
              {...register('password')}
              error={!!errors.password}
              helperText={errors.password?.message}
            />
            <TextField
              margin="normal"
              required
              fullWidth
              label="Confirm Password"
              type="password"
              id="confirmPassword"
              autoComplete="new-password"
              {...register('confirmPassword')}
              error={!!errors.confirmPassword}
              helperText={errors.confirmPassword?.message}
            />
            <Button
              type="submit"
              fullWidth
              variant="contained"
              sx={{ mt: 3, mb: 2 }}
              disabled={isSubmitting}
            >
              {isSubmitting ? 'Signing up...' : 'Sign Up'}
            </Button>
            <Box sx={{ display: 'flex', justifyContent: 'flex-end' }}>
              <Link href="/login" passHref>
                <Typography variant="body2" color="primary" component="a">
                  Already have an account? Sign in
                </Typography>
              </Link>
            </Box>
          </Box>
        </Paper>
      </Box>
    </Container>
  );
}

// src/routes/auth/register/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { User, Mail, Lock } from 'lucide-svelte';
	
	let username = $state('');
	let email = $state('');
	let password = $state('');
	let confirmPassword = $state('');
	let error = $state('');
	let submitting = $state(false);
	
	async function handleRegister() {
		try {
			submitting = true;
			error = '';
			
			// Validate passwords match
			if (password !== confirmPassword) {
				error = 'Passwords do not match';
				submitting = false;
				return;
			}
			
			const response = await fetch('/api/auth/register', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					username,
					email,
					password
				})
			});
			
			const data = await response.json();
			
			if (!response.ok) {
				error = data.error || 'Failed to create account';
				return;
			}
			
			// Redirect to login on successful registration
			goto('/auth/login');
		} catch (err) {
			console.error('Registration error:', err);
			error = 'An unexpected error occurred';
		} finally {
			submitting = false;
		}
	}
</script>

<svelte:head>
	<title>Register - Journal App</title>
</svelte:head>

<div class="min-h-screen flex flex-col items-center justify-center p-4 bg-base-200">
	<div class="w-full max-w-md p-6 bg-base-100 rounded-lg shadow-lg border border-base-300">
		<div class="text-center mb-6">
			<h1 class="text-3xl font-bold text-base-content">Create Account</h1>
			<p class="text-base-content/70 mt-1">Start your personal journey today</p>
		</div>
		
		{#if error}
			<div class="alert alert-error mb-4">
				<span>{error}</span>
			</div>
		{/if}
		
		<form onsubmit={(e) => { e.preventDefault(); handleRegister(); }} class="space-y-4">
			<div class="form-control">
				<label for="username" class="label">
					<span class="label-text">Username</span>
				</label>
				<div class="relative">
					<div class="absolute left-3 top-1/2 transform -translate-y-1/2 opacity-70">
						<User size={18} />
					</div>
					<input 
						type="text" 
						id="username"
						class="input input-bordered w-full pl-10" 
						placeholder="username"
						bind:value={username}
						required
					/>
				</div>
			</div>
			
			<div class="form-control">
				<label for="email" class="label">
					<span class="label-text">Email</span>
				</label>
				<div class="relative">
					<div class="absolute left-3 top-1/2 transform -translate-y-1/2 opacity-70">
						<Mail size={18} />
					</div>
					<input 
						type="email" 
						id="email"
						class="input input-bordered w-full pl-10" 
						placeholder="your@email.com"
						bind:value={email}
						required
					/>
				</div>
			</div>
			
			<div class="form-control">
				<label for="password" class="label">
					<span class="label-text">Password</span>
				</label>
				<div class="relative">
					<div class="absolute left-3 top-1/2 transform -translate-y-1/2 opacity-70">
						<Lock size={18} />
					</div>
					<input 
						type="password" 
						id="password"
						class="input input-bordered w-full pl-10" 
						placeholder="Password (min 8 characters)"
						minlength="8"
						bind:value={password}
						required
					/>
				</div>
			</div>
			
			<div class="form-control">
				<label for="confirm-password" class="label">
					<span class="label-text">Confirm Password</span>
				</label>
				<div class="relative">
					<div class="absolute left-3 top-1/2 transform -translate-y-1/2 opacity-70">
						<Lock size={18} />
					</div>
					<input 
						type="password" 
						id="confirm-password"
						class="input input-bordered w-full pl-10" 
						placeholder="Confirm your password"
						bind:value={confirmPassword}
						required
					/>
				</div>
			</div>
			
			<div class="form-control mt-6">
				<button 
					type="submit" 
					class="btn btn-primary w-full" 
					disabled={submitting}
				>
					{#if submitting}
						<span class="loading loading-spinner loading-sm"></span>
						Creating Account...
					{:else}
						Register
					{/if}
				</button>
			</div>
			
			<div class="text-center text-sm mt-4">
				Already have an account? 
				<a href="/auth/login" class="text-primary hover:underline">Login</a>
			</div>
		</form>
	</div>
</div>
