// frontend/src/routes/dashboard/journal/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { format } from 'date-fns';
	import api, { type JournalEntry } from '$lib/api.js';
	import LoadingSpinner from '$lib/components/LoadingSpinner.svelte';
	import Alert from '$lib/components/Alert.svelte';

	let entries = $state<JournalEntry[]>([]);
	let isLoading = $state(true);
	let error = $state('');
	let searchTerm = $state('');
	let selectedTag = $state('');
	let allTags = $state<string[]>([]);

	onMount(async () => {
		await loadEntries();
	});

	async function loadEntries() {
		isLoading = true;
		error = '';

		try {
			const params: any = {};
			if (selectedTag) params.tag = selectedTag;
			
			entries = await api.getJournalEntries(params);
			
			// Extract all unique tags
			const tagSet = new Set<string>();
			entries.forEach(entry => {
				entry.tags?.forEach(tag => tagSet.add(tag));
			});
			allTags = Array.from(tagSet).sort();
			
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load journal entries';
		} finally {
			isLoading = false;
		}
	}

	function formatDate(dateString: string) {
		return format(new Date(dateString), 'MMM d, yyyy');
	}

	function formatTime(dateString: string) {
		return format(new Date(dateString), 'h:mm a');
	}

	function clearError() {
		error = '';
	}

	async function handleTagFilter(tag: string) {
		selectedTag = tag === selectedTag ? '' : tag;
		await loadEntries();
	}

	// Filter entries based on search term
	const filteredEntries = $derived(() => {
		if (!searchTerm.trim()) return entries;
		
		const search = searchTerm.toLowerCase();
		return entries.filter(entry => 
			entry.title.toLowerCase().includes(search) ||
			entry.content.toLowerCase().includes(search) ||
			entry.tags?.some(tag => tag.toLowerCase().includes(search))
		);
	});
</script>

<svelte:head>
	<title>My Journal Entries - Journal</title>
</svelte:head>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
		<div>
			<h1 class="text-3xl font-bold text-base-content">My Journal Entries</h1>
			<p class="text-base-content/70 mt-1">
				{entries.length} {entries.length === 1 ? 'entry' : 'entries'}
			</p>
		</div>
		<a href="/journal/new" class="btn btn-primary">
			<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
			</svg>
			New Entry
		</a>
	</div>

	{#if error}
		<Alert message={error} type="error" onDismiss={clearError} />
	{/if}

	<!-- Filters -->
	<div class="card bg-base-100 shadow-lg">
		<div class="card-body">
			<div class="flex flex-col sm:flex-row gap-4">
				<!-- Search -->
				<div class="form-control flex-1">
					<label class="label" for="search">
						<span class="label-text">Search entries</span>
					</label>
					<input
						id="search"
						type="text"
						bind:value={searchTerm}
						class="input input-bordered focus-ring"
						placeholder="Search by title, content, or tags..."
					/>
				</div>

				<!-- Tag filter -->
				{#if allTags.length > 0}
					<div class="form-control">
						<label class="label">
							<span class="label-text">Filter by tag</span>
						</label>
						<div class="flex flex-wrap gap-2">
							{#each allTags.slice(0, 6) as tag}
								<button
									class="badge badge-lg cursor-pointer transition-colors {selectedTag === tag ? 'badge-primary' : 'badge-ghost hover:badge-neutral'}"
									onclick={() => handleTagFilter(tag)}
								>
									{tag}
								</button>
							{/each}
							{#if selectedTag}
								<button
									class="badge badge-lg badge-error cursor-pointer"
									onclick={() => handleTagFilter('')}
									title="Clear filter"
								>
									✕
								</button>
							{/if}
						</div>
					</div>
				{/if}
			</div>
		</div>
	</div>

	<!-- Entries -->
	{#if isLoading}
		<div class="flex justify-center py-8">
			<LoadingSpinner size="lg" />
		</div>
	{:else if filteredEntries.length === 0}
		<div class="card bg-base-100 shadow-lg">
			<div class="card-body text-center py-16">
				{#if entries.length === 0}
					<svg class="w-16 h-16 mx-auto text-base-content/30" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
					</svg>
					<h3 class="text-xl font-medium text-base-content mt-4">No journal entries yet</h3>
					<p class="text-base-content/70 mt-2">Start your journaling journey today!</p>
					<a href="/journal/new" class="btn btn-primary mt-6">
						Write Your First Entry
					</a>
				{:else}
					<svg class="w-16 h-16 mx-auto text-base-content/30" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
					</svg>
					<h3 class="text-xl font-medium text-base-content mt-4">No matching entries</h3>
					<p class="text-base-content/70 mt-2">Try adjusting your search or filter criteria</p>
					<button 
						class="btn btn-ghost mt-4"
						onclick={() => { searchTerm = ''; selectedTag = ''; }}
					>
						Clear Filters
					</button>
				{/if}
			</div>
		</div>
	{:else}
		<div class="grid gap-4">
			{#each filteredEntries as entry}
				<div class="card bg-base-100 shadow-lg hover:shadow-xl transition-shadow">
					<div class="card-body">
						<div class="flex items-start justify-between">
							<div class="flex-1">
								<h2 class="card-title text-lg">
									<a href="/journal/{entry.id}" class="hover:text-primary transition-colors">
										{entry.title}
									</a>
								</h2>
								<p class="text-base-content/70 mt-2 line-clamp-3">
									{entry.content.length > 200 ? entry.content.substring(0, 200) + '...' : entry.content}
								</p>
								<div class="flex items-center gap-4 mt-4 text-sm text-base-content/50">
									<span>{formatDate(entry.created_at)}</span>
									<span>{formatTime(entry.created_at)}</span>
									{#if entry.is_private}
										<span class="badge badge-sm badge-ghost">
											<svg class="w-3 h-3 mr-1" fill="currentColor" viewBox="0 0 24 24">
												<path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4z"/>
											</svg>
											Private
										</span>
									{/if}
								</div>
							</div>
							<div class="flex flex-col items-end gap-2">
								{#if entry.mood_score}
									<div class="badge badge-primary badge-sm">
										Mood: {entry.mood_score}/10
									</div>
								{/if}
								<div class="dropdown dropdown-end">
									<div tabindex="0" role="button" class="btn btn-ghost btn-sm btn-circle">
										<svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
											<path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/>
										</svg>
									</div>
									<ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-32 z-10">
										<li><a href="/journal/{entry.id}">View</a></li>
										<li><a href="/journal/{entry.id}/edit">Edit</a></li>
									</ul>
								</div>
							</div>
						</div>
						{#if entry.tags && entry.tags.length > 0}
							<div class="flex flex-wrap gap-2 mt-4">
								{#each entry.tags as tag}
									<button
										class="badge badge-sm badge-ghost hover:badge-neutral cursor-pointer"
										onclick={() => handleTagFilter(tag)}
									>
										{tag}
									</button>
								{/each}
							</div>
						{/if}
					</div>
				</div>
			{/each}
		</div>
	{/if}
</div>

// frontend/src/app/dashboard/journal/page.tsx
'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { BookOpen, Plus, Search, Calendar, Tag } from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { JournalEntry } from '@/types'
import { LoadingSpinner } from '@/components/LoadingSpinner'
import { ErrorMessage } from '@/components/ErrorMessage'
import { dateUtils, textUtils } from '@/utils'

export default function JournalPage() {
  const [entries, setEntries] = useState<JournalEntry[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [searchQuery, setSearchQuery] = useState('')
  const [sortBy, setSortBy] = useState<'newest' | 'oldest'>('newest')

  useEffect(() => {
    const loadEntries = async () => {
      try {
        setIsLoading(true)
        setError(null)
        
        const response = await apiClient.getJournalEntries()
        if (response.success && response.data) {
          setEntries(response.data)
        } else {
          setError(response.error || 'Failed to load journal entries')
        }
      } catch (err) {
        console.error('Error loading journal entries:', err)
        setError('Unable to load journal entries')
      } finally {
        setIsLoading(false)
      }
    }

    loadEntries()
  }, [])

  // Filter and sort entries
  const filteredEntries = entries
    .filter(entry => {
      if (!searchQuery) return true
      const searchLower = searchQuery.toLowerCase()
      return (
        entry.title?.toLowerCase().includes(searchLower) ||
        entry.synopsis?.toLowerCase().includes(searchLower) ||
        entry.conversationData?.messages?.some(msg => 
          msg.content.toLowerCase().includes(searchLower)
        )
      )
    })
    .sort((a, b) => {
      const dateA = new Date(a.createdAt).getTime()
      const dateB = new Date(b.createdAt).getTime()
      return sortBy === 'newest' ? dateB - dateA : dateA - dateB
    })

  if (isLoading) {
    return <LoadingSpinner size="lg" />
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-base-content flex items-center gap-2">
            <BookOpen className="h-6 w-6 text-journal-primary" />
            Journal Entries
          </h1>
          <p className="text-base-content/60 mt-1">
            {entries.length} {entries.length === 1 ? 'entry' : 'entries'} total
          </p>
        </div>
        
        <Link href="/dashboard/journal/new" className="btn btn-primary">
          <Plus className="h-4 w-4 mr-2" />
          New Entry
        </Link>
      </div>

      {/* Search and Filters */}
      <div className="card bg-base-100 shadow-sm">
        <div className="card-body">
          <div className="flex flex-col sm:flex-row gap-4">
            {/* Search */}
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-base-content/40" />
              <input
                type="text"
                placeholder="Search entries..."
                className="input input-bordered w-full pl-10"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            
            {/* Sort */}
            <select
              className="select select-bordered w-full sm:w-48"
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as 'newest' | 'oldest')}
            >
              <option value="newest">Newest First</option>
              <option value="oldest">Oldest First</option>
            </select>
          </div>
        </div>
      </div>

      {/* Error Message */}
      {error && (
        <ErrorMessage 
          message={error} 
          onRetry={() => window.location.reload()}
        />
      )}

      {/* Entries List */}
      {filteredEntries.length === 0 ? (
        <div className="card bg-base-100 shadow-sm">
          <div className="card-body text-center py-12">
            <BookOpen className="h-16 w-16 text-base-content/20 mx-auto mb-4" />
            {searchQuery ? (
              <>
                <h3 className="text-lg font-semibold text-base-content mb-2">
                  No entries found
                </h3>
                <p className="text-base-content/60 mb-4">
                  Try adjusting your search terms or create a new entry.
                </p>
              </>
            ) : (
              <>
                <h3 className="text-lg font-semibold text-base-content mb-2">
                  Start Your Journal Journey
                </h3>
                <p className="text-base-content/60 mb-4">
                  Write your first journal entry and begin reflecting on your personal growth.
                </p>
              </>
            )}
            <Link href="/dashboard/journal/new" className="btn btn-primary">
              <Plus className="h-4 w-4 mr-2" />
              Write Your First Entry
            </Link>
          </div>
        </div>
      ) : (
        <div className="grid gap-4">
          {filteredEntries.map((entry) => (
            <Link
              key={entry.id}
              href={`/dashboard/journal/${entry.id}`}
              className="card bg-base-100 shadow-sm hover:shadow-md transition-shadow"
            >
              <div className="card-body">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold text-base-content line-clamp-1">
                      {entry.title || 'Untitled Entry'}
                    </h3>
                    {entry.synopsis && (
                      <p className="text-sm text-base-content/70 mt-1 line-clamp-1">
                        {entry.synopsis}
                      </p>
                    )}
                  </div>
                  <div className="flex items-center text-xs text-base-content/60 ml-4">
                    <Calendar className="h-3 w-3 mr-1" />
                    {dateUtils.formatDate(entry.createdAt)}
                  </div>
                </div>
                
                <p className="text-base-content/80 line-clamp-3 mb-3">
                  {entry.conversationData?.messages?.length > 0 
                    ? textUtils.truncate(entry.conversationData.messages[0].content, 200)
                    : entry.summary || 'No content'}
                </p>
                
                <div className="flex items-center justify-between">
                  <div className="flex items-center text-xs text-base-content/60">
                    <span>
                      {entry.conversationData?.messages 
                        ? entry.conversationData.messages
                            .filter(msg => msg.role === 'user')
                            .reduce((total, msg) => total + textUtils.countWords(msg.content), 0)
                        : 0} words
                    </span>
                    <span className="mx-2">•</span>
                    <span>{dateUtils.getRelativeTime(entry.createdAt)}</span>
                  </div>
                  
                  {entry.summary && (
                    <div className="flex items-center text-xs text-journal-primary">
                      <Tag className="h-3 w-3 mr-1" />
                      Analyzed
                    </div>
                  )}
                </div>
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  )
}
