// src/routes/journal/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { BookOpen, Plus, Calendar, Tag, Search, X, Filter } from 'lucide-svelte';
	import type { JournalEntryWithTags } from '$lib/types.js';
	import type { ContentTag } from '$lib/server/db/schema';
	
	let entries: JournalEntryWithTags[] = $state([]);
	let tags: ContentTag[] = $state([]);
	let selectedTagIds: string[] = $state([]);
	let searchQuery = $state('');
	let loading = $state(true);
	let tagsLoading = $state(true); 
	let page = $state(1);
	let hasMore = $state(true);
	let filterExpanded = $state(false);
	
	onMount(async () => {
		await Promise.all([loadEntries(), loadTags()]);
	});
	
	async function loadTags() {
		try {
			tagsLoading = true;
			const response = await fetch('/api/tags');
			
			if (response.ok) {
				const data = await response.json();
				tags = data.tags || [];
			}
		} catch (error) {
			console.error('Error loading tags:', error);
		} finally {
			tagsLoading = false;
		}
	}
	
	async function loadEntries(reset = false) {
		try {
			loading = true;
			const currentPage = reset ? 1 : page;
			const response = await fetch(`/api/journal?page=${currentPage}&limit=10`);
			
			if (response.ok) {
				const data = await response.json();
				if (reset) {
					entries = data.entries;
				} else {
					entries = [...entries, ...data.entries];
				}
				hasMore = data.entries.length === 10;
				page = currentPage + 1;
			}
		} catch (error) {
			console.error('Error loading journal entries:', error);
		} finally {
			loading = false;
		}
	}
	
	function formatDate(date: string | Date) {
		const dateObj = typeof date === 'string' ? new Date(date) : date;
		return dateObj.toLocaleDateString('en-US', {
			weekday: 'long',
			year: 'numeric',
			month: 'long',
			day: 'numeric'
		});
	}
	
	function formatTimeAgo(date: string | Date) {
		const dateObj = typeof date === 'string' ? new Date(date) : date;
		const now = new Date();
		const diffMs = now.getTime() - dateObj.getTime();
		const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
		
		if (diffDays === 0) return 'Today';
		if (diffDays === 1) return 'Yesterday';
		if (diffDays < 7) return `${diffDays} days ago`;
		if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`;
		return `${Math.floor(diffDays / 30)} months ago`;
	}
</script>

<svelte:head>
	<title>Journal - Journal App</title>
</svelte:head>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
		<div>
			<h1 class="text-3xl font-bold text-base-content">Journal</h1>
			<p class="text-base-content/70 mt-1">Your personal reflection space</p>
		</div>
		<a href="/journal/new" class="btn btn-primary gap-2">
			<Plus size={20} />
			New Entry
		</a>
	</div>
	
	<!-- Search & Filter -->
	<div class="space-y-3">
		<!-- Search Bar -->
		<div class="flex items-center gap-2">
			<div class="relative flex-1">
				<input
					type="text"
					class="input input-bordered w-full pl-10 pr-10"
					placeholder="Search journal entries..."
					bind:value={searchQuery}
				/>
				<Search size={18} class="absolute left-3 top-1/2 -translate-y-1/2 text-base-content/50" />
				{#if searchQuery}
					<button 
						class="absolute right-3 top-1/2 -translate-y-1/2 text-base-content/50 hover:text-base-content"
						onclick={() => searchQuery = ''}
					>
						<X size={16} />
					</button>
				{/if}
			</div>
			
			<button 
				class="btn btn-outline {filterExpanded ? 'btn-primary' : ''} gap-1"
				onclick={() => filterExpanded = !filterExpanded}
			>
				<Filter size={18} />
				{#if selectedTagIds.length > 0}
					<span class="badge badge-sm">{selectedTagIds.length}</span>
				{/if}
			</button>
		</div>
		
		<!-- Tags Filters -->
		{#if filterExpanded}
			<div class="bg-base-200 p-4 rounded-lg border border-base-300">
				<div class="mb-2 flex items-center justify-between">
					<h3 class="font-medium flex items-center gap-2">
						<Tag size={16} />
						Filter by Tags
					</h3>
					{#if selectedTagIds.length > 0}
						<button 
							class="btn btn-sm btn-ghost text-xs"
							onclick={() => selectedTagIds = []}
						>
							Clear All
						</button>
					{/if}
				</div>
				
				{#if tagsLoading}
					<div class="flex justify-center py-4">
						<span class="loading loading-spinner loading-sm"></span>
					</div>
				{:else if tags.length === 0}
					<div class="text-center py-4 text-sm text-base-content/70">
						You haven't created any tags yet.
						<a href="/tags/new" class="link link-primary">Create your first tag</a>
					</div>
				{:else}
					<div class="flex flex-wrap gap-2">
						{#each tags as tag}
							<button
								class="badge {selectedTagIds.includes(tag.id) ? 'badge-primary' : 'badge-outline'} cursor-pointer"
								onclick={() => {
									if (selectedTagIds.includes(tag.id)) {
										selectedTagIds = selectedTagIds.filter(id => id !== tag.id);
									} else {
										selectedTagIds = [...selectedTagIds, tag.id];
									}
								}}
							>
								{tag.name}
							</button>
						{/each}
						<a href="/tags" class="badge badge-ghost badge-sm gap-1">
							<Plus size={10} />
							Manage Tags
						</a>
					</div>
				{/if}
			</div>
		{/if}
	</div>

	<!-- Entries List -->
	{#if loading && entries.length === 0}
		<div class="flex justify-center py-12">
			<span class="loading loading-spinner loading-lg"></span>
		</div>
	{:else if entries.length === 0}
		<div class="text-center py-16">
			<BookOpen size={64} class="mx-auto text-base-content/30 mb-4" />
			<h2 class="text-xl font-semibold mb-2">No journal entries yet</h2>
			<p class="text-base-content/70 mb-6">Start your journaling journey by creating your first entry</p>
			<a href="/journal/new" class="btn btn-primary gap-2">
				<Plus size={20} />
				Start Journaling
			</a>
		</div>
	{:else}
		<div class="space-y-4">
			{#each entries as entry}
				<div class="card bg-base-100 border border-base-300 hover:border-base-400 transition-colors">
					<div class="card-body">
						<div class="flex items-start justify-between">
							<div class="flex-1">
								<div class="flex items-center gap-3 mb-2">
									<Calendar size={16} class="text-base-content/50" />
									<span class="text-sm text-base-content/70">
										{formatDate(entry.createdAt)}
									</span>
									<span class="text-xs text-base-content/50">
										({formatTimeAgo(entry.createdAt)})
									</span>
								</div>
								
								<a href="/journal/{entry.id}" class="block hover:text-primary transition-colors">
									<h2 class="text-xl font-semibold mb-2">
										{entry.title || 'Untitled Entry'}
									</h2>
								</a>
								
								{#if entry.synopsis}
									<p class="text-base-content/80 mb-3">
										{entry.synopsis}
									</p>
								{/if}
								
								<!-- Tags -->
								<div class="flex flex-wrap gap-2 mb-3">
									{#if entry.contentTags?.length > 0}
										{#each entry.contentTags as tag}
											<span class="badge badge-outline badge-sm gap-1">
												<Tag size={12} />
												{tag.name}
											</span>
										{/each}
									{/if}
									
									{#if entry.toneTags?.length > 0}
										{#each entry.toneTags as tag}
											<span class="badge badge-primary badge-sm">
												{tag.name}
											</span>
										{/each}
									{/if}
									
									{#if entry.characterTags?.length > 0}
										{#each entry.characterTags as tag}
											<span class="badge badge-secondary badge-sm">
												{tag.name} +{tag.xpGained}XP
											</span>
										{/each}
									{/if}
								</div>
							</div>
							
							<!-- Processing Status -->
							<div class="flex flex-col items-end gap-2">
								{#if entry.isProcessed}
									<div class="badge badge-success badge-sm">Processed</div>
								{:else if entry.conversationData?.length > 0}
									<div class="badge badge-warning badge-sm">In Progress</div>
								{:else}
									<div class="badge badge-ghost badge-sm">Draft</div>
								{/if}
								
								<a href="/journal/{entry.id}" class="btn btn-sm btn-outline">
									View Entry
								</a>
							</div>
						</div>
					</div>
				</div>
			{/each}
		</div>

		<!-- Load More -->
		{#if hasMore}
			<div class="text-center pt-6">
				{#if loading}
					<span class="loading loading-spinner loading-md"></span>
				{:else}
					<button class="btn btn-outline" onclick={() => loadEntries()}>
						Load More Entries
					</button>
				{/if}
			</div>
		{/if}
	{/if}
</div>

// frontend/src/app/dashboard/journal/page.tsx
'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { BookOpen, Plus, Search, Calendar, Tag } from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { JournalEntryWithTags } from '@/types'
import { LoadingSpinner } from '@/components/LoadingSpinner'
import { ErrorMessage } from '@/components/ErrorMessage'
import { TagDisplay } from '@/components/TagDisplay'
import { dateUtils, textUtils } from '@/utils'

export default function JournalPage() {
  const [entries, setEntries] = useState<JournalEntryWithTags[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [searchQuery, setSearchQuery] = useState('')
  const [sortBy, setSortBy] = useState<'newest' | 'oldest'>('newest')

  useEffect(() => {
    const loadEntries = async () => {
      try {
        setIsLoading(true)
        setError(null)
        
        const response = await apiClient.getJournalEntriesWithTags()
        if (response.success && response.data) {
          setEntries(response.data)
        } else {
          setError(response.error || 'Failed to load journal entries')
        }
      } catch (err) {
        console.error('Error loading journal entries:', err)
        setError('Unable to load journal entries')
      } finally {
        setIsLoading(false)
      }
    }

    loadEntries()
  }, [])

  // Filter and sort entries
  const filteredEntries = entries
    .filter(entry => {
      if (!searchQuery) return true
      const searchLower = searchQuery.toLowerCase()
      return (
        entry.title?.toLowerCase().includes(searchLower) ||
        entry.synopsis?.toLowerCase().includes(searchLower) ||
        entry.conversationData?.messages?.some((msg: any) => 
          msg.content.toLowerCase().includes(searchLower)
        )
      )
    })
    .sort((a, b) => {
      const dateA = new Date(a.createdAt).getTime()
      const dateB = new Date(b.createdAt).getTime()
      return sortBy === 'newest' ? dateB - dateA : dateA - dateB
    })

  if (isLoading) {
    return <LoadingSpinner size="lg" />
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-base-content flex items-center gap-2">
            <BookOpen className="h-6 w-6 text-journal-primary" />
            Journal Entries
          </h1>
          <p className="text-base-content/60 mt-1">
            {entries.length} {entries.length === 1 ? 'entry' : 'entries'} total
          </p>
        </div>
        
        <Link href="/dashboard/journal/new" className="btn btn-primary">
          <Plus className="h-4 w-4 mr-2" />
          New Entry
        </Link>
      </div>

      {/* Search and Filters */}
      <div className="card bg-base-100 shadow-sm">
        <div className="card-body">
          <div className="flex flex-col sm:flex-row gap-4">
            {/* Search */}
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-base-content/40" />
              <input
                type="text"
                placeholder="Search entries..."
                className="input input-bordered w-full pl-10"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
            
            {/* Sort */}
            <select
              className="select select-bordered w-full sm:w-48"
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as 'newest' | 'oldest')}
            >
              <option value="newest">Newest First</option>
              <option value="oldest">Oldest First</option>
            </select>
          </div>
        </div>
      </div>

      {/* Error Message */}
      {error && (
        <ErrorMessage 
          message={error} 
          onRetry={() => window.location.reload()}
        />
      )}

      {/* Entries List */}
      {filteredEntries.length === 0 ? (
        <div className="card bg-base-100 shadow-sm">
          <div className="card-body text-center py-12">
            <BookOpen className="h-16 w-16 text-base-content/20 mx-auto mb-4" />
            {searchQuery ? (
              <>
                <h3 className="text-lg font-semibold text-base-content mb-2">
                  No entries found
                </h3>
                <p className="text-base-content/60 mb-4">
                  Try adjusting your search terms or create a new entry.
                </p>
              </>
            ) : (
              <>
                <h3 className="text-lg font-semibold text-base-content mb-2">
                  Start Your Journal Journey
                </h3>
                <p className="text-base-content/60 mb-4">
                  Write your first journal entry and begin reflecting on your personal growth.
                </p>
              </>
            )}
            <Link href="/dashboard/journal/new" className="btn btn-primary">
              <Plus className="h-4 w-4 mr-2" />
              Write Your First Entry
            </Link>
          </div>
        </div>
      ) : (
        <div className="grid gap-4">
          {filteredEntries.map((entry) => (
            <Link
              key={entry.id}
              href={`/dashboard/journal/${entry.id}`}
              className="card bg-base-100 shadow-sm hover:shadow-md transition-shadow"
            >
              <div className="card-body">
                <div className="flex items-start justify-between mb-3">
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold text-base-content line-clamp-1">
                      {entry.title || 'Untitled Entry'}
                    </h3>
                    {entry.synopsis && (
                      <p className="text-sm text-base-content/70 mt-1 line-clamp-1">
                        {entry.synopsis}
                      </p>
                    )}
                  </div>
                  <div className="flex items-center text-xs text-base-content/60 ml-4">
                    <Calendar className="h-3 w-3 mr-1" />
                    {dateUtils.formatDate(entry.createdAt)}
                  </div>
                </div>
                
                <p className="text-base-content/80 line-clamp-3 mb-3">
                  {entry.conversationData?.messages?.length > 0 
                    ? textUtils.truncate(entry.conversationData.messages[0].content, 200)
                    : entry.summary || 'No content'}
                </p>
                
                {/* Tags */}
                <TagDisplay 
                  contentTags={entry.contentTags}
                  toneTags={entry.toneTags}
                  characterStats={entry.characterStats}
                  size="sm"
                  className="mb-3"
                />
                
                <div className="flex items-center justify-between">
                  <div className="flex items-center text-xs text-base-content/60">
                    <span>
                      {entry.conversationData?.messages 
                        ? entry.conversationData.messages
                            .filter((msg: any) => msg.role === 'user')
                            .reduce((total: number, msg: any) => total + textUtils.countWords(msg.content), 0)
                        : 0} words
                    </span>
                    <span className="mx-2">•</span>
                    <span>{dateUtils.getRelativeTime(entry.createdAt)}</span>
                  </div>
                  
                  {entry.summary && (
                    <div className="flex items-center text-xs text-journal-primary">
                      <Tag className="h-3 w-3 mr-1" />
                      Analyzed
                    </div>
                  )}
                </div>
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  )
}
