// frontend/src/routes/quests/new/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { questsApi } from '$lib/api/quests';
  import type { CreateQuestRequest } from '$lib/types/quest';
  import { ArrowLeft, Save, Target } from 'lucide-svelte';

  // Form state
  let formData: CreateQuestRequest = {
    title: '',
    summary: '',
    startDate: new Date().toISOString().split('T')[0], // Today's date in YYYY-MM-DD format
    endDate: '',
  };

  let isSubmitting = false;
  let error = '';

  async function handleSubmit() {
    try {
      error = '';
      isSubmitting = true;

      // Basic validation
      if (!formData.title.trim()) {
        error = 'Title is required';
        return;
      }

      if (!formData.startDate) {
        error = 'Start date is required';
        return;
      }

      // Validate end date is after start date if provided
      if (formData.endDate && formData.endDate <= formData.startDate) {
        error = 'End date must be after start date';
        return;
      }

      // Clean up form data
      const questData: CreateQuestRequest = {
        title: formData.title.trim(),
        startDate: formData.startDate,
      };

      if (formData.summary?.trim()) {
        questData.summary = formData.summary.trim();
      }

      if (formData.endDate) {
        questData.endDate = formData.endDate;
      }

      // Create the quest
      const quest = await questsApi.createQuest(questData);

      // Redirect to the quest detail page
      goto(`/quests/${quest.id}`);
    } catch (err) {
      console.error('Failed to create quest:', err);
      error = err instanceof Error ? err.message : 'Failed to create quest';
    } finally {
      isSubmitting = false;
    }
  }

  function handleCancel() {
    goto('/quests');
  }
</script>

<svelte:head>
  <title>New Quest - Life Journal</title>
</svelte:head>

<div class="mx-auto max-w-2xl p-4">
  <!-- Page Header -->
  <div class="mb-6 flex items-center gap-4">
    <button class="btn btn-ghost btn-sm" on:click={handleCancel} disabled={isSubmitting}>
      <ArrowLeft class="h-4 w-4" />
      Back
    </button>
    <div>
      <h1 class="flex items-center gap-3 text-3xl font-bold">
        <Target class="text-primary h-8 w-8" />
        New Quest
      </h1>
      <p class="text-base-content/60 mt-1">Create a new life adventure to track</p>
    </div>
  </div>

  <!-- Error Alert -->
  {#if error}
    <div class="alert alert-error mb-6">
      <span>{error}</span>
    </div>
  {/if}

  <!-- Quest Form -->
  <form on:submit|preventDefault={handleSubmit} class="space-y-6">
    <div class="card bg-base-100 shadow-sm">
      <div class="card-body space-y-6">
        <!-- Quest Title -->
        <div class="form-control">
          <label class="label" for="title">
            <span class="label-text font-medium">Quest Title *</span>
          </label>
          <input
            id="title"
            type="text"
            placeholder="Enter your quest title..."
            class="input input-bordered w-full"
            bind:value={formData.title}
            disabled={isSubmitting}
            required
          />
          <div class="label">
            <span class="label-text-alt text-base-content/60"> Give your quest a memorable and inspiring name </span>
          </div>
        </div>

        <!-- Quest Summary -->
        <div class="form-control">
          <label class="label" for="summary">
            <span class="label-text font-medium">Summary</span>
          </label>
          <textarea
            id="summary"
            placeholder="Describe what this quest is about..."
            class="textarea textarea-bordered h-24 resize-none"
            bind:value={formData.summary}
            disabled={isSubmitting}
          ></textarea>
          <div class="label">
            <span class="label-text-alt text-base-content/60"> Optional description of your quest goals and motivation </span>
          </div>
        </div>

        <!-- Date Range -->
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <!-- Start Date -->
          <div class="form-control">
            <label class="label" for="startDate">
              <span class="label-text font-medium">Start Date *</span>
            </label>
            <input id="startDate" type="date" class="input input-bordered w-full" bind:value={formData.startDate} disabled={isSubmitting} required />
          </div>

          <!-- End Date -->
          <div class="form-control">
            <label class="label" for="endDate">
              <span class="label-text font-medium">End Date</span>
            </label>
            <input
              id="endDate"
              type="date"
              class="input input-bordered w-full"
              bind:value={formData.endDate}
              disabled={isSubmitting}
              min={formData.startDate}
            />
            <div class="label">
              <span class="label-text-alt text-base-content/60"> Optional target completion date </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Action Buttons -->
    <div class="flex flex-col gap-3 sm:flex-row sm:justify-end">
      <button type="button" class="btn btn-outline" on:click={handleCancel} disabled={isSubmitting}> Cancel </button>
      <button type="submit" class="btn btn-primary" disabled={isSubmitting || !formData.title.trim()}>
        {#if isSubmitting}
          <span class="loading loading-spinner loading-sm"></span>
          Creating Quest...
        {:else}
          <Save class="h-4 w-4" />
          Create Quest
        {/if}
      </button>
    </div>
  </form>
</div>

// frontend/src/app/dashboard/journal/new/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import TextareaAutosize from 'react-textarea-autosize'
import { 
  BookOpen, 
  Save, 
  ArrowLeft, 
  Sparkles, 
  FlaskConical,
  MessageCircle 
} from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { Experiment } from '@/types'
import { LoadingSpinner } from '@/components/LoadingSpinner'
import { ErrorMessage } from '@/components/ErrorMessage'

// Zod schema for form validation
const JournalEntryFormSchema = z.object({
  initialMessage: z.string()
    .min(10, 'Please write at least 10 characters')
    .max(10000, 'Entry is too long (max 10,000 characters)'),
  experimentIds: z.array(z.string().uuid()),
})

type JournalEntryFormData = z.infer<typeof JournalEntryFormSchema>

export default function NewJournalEntryPage() {
  const [isLoading, setIsLoading] = useState(false)
  const [isCreating, setIsCreating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [experiments, setExperiments] = useState<Experiment[]>([])
  const [showExperimentSelector, setShowExperimentSelector] = useState(false)
  const router = useRouter()

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors },
  } = useForm<JournalEntryFormData>({
    resolver: zodResolver(JournalEntryFormSchema),
    mode: 'onChange',
    defaultValues: {
      initialMessage: '',
      experimentIds: [],
    }
  })

  const initialMessage = watch('initialMessage')
  const selectedExperimentIds = watch('experimentIds')

  // Load experiments on mount
  useEffect(() => {
    const loadExperiments = async () => {
      try {
        setIsLoading(true)
        const response = await apiClient.getExperiments()
        if (response.success && response.data) {
          // Filter for active experiments
          const now = new Date()
          const activeExperiments = response.data.filter(exp => {
            const startDate = new Date(exp.startDate)
            const endDate = new Date(exp.endDate)
            return now >= startDate && now <= endDate
          })
          setExperiments(activeExperiments)
        }
      } catch (err) {
        console.error('Error loading experiments:', err)
      } finally {
        setIsLoading(false)
      }
    }

    loadExperiments()
  }, [])

  const onSubmit = async (data: JournalEntryFormData) => {
    setIsCreating(true)
    setError(null)

    try {
      const response = await apiClient.createJournalEntry({
        entryDate: new Date().toISOString(),
        initialMessage: data.initialMessage,
        experimentIds: data.experimentIds,
      })

      if (response.success && response.data) {
        // Redirect to the created entry
        router.push(`/dashboard/journal/${response.data.id}`)
      } else {
        setError(response.error || 'Failed to create journal entry')
      }
    } catch (err) {
      console.error('Error creating journal entry:', err)
      setError('Unable to create journal entry. Please try again.')
    } finally {
      setIsCreating(false)
    }
  }

  const selectedExperiment = experiments.find(exp => selectedExperimentIds.includes(exp.id))
  const wordCount = initialMessage ? initialMessage.trim().split(/\s+/).filter((word: string) => word.length > 0).length : 0

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <Link 
            href="/dashboard/journal" 
            className="btn btn-ghost btn-circle"
            aria-label="Back to journal"
          >
            <ArrowLeft className="h-5 w-5" />
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-base-content flex items-center gap-2">
              <BookOpen className="h-6 w-6 text-journal-primary" />
              New Journal Entry
            </h1>
            <p className="text-base-content/60">Share your thoughts and reflections</p>
          </div>
        </div>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        <div className="card bg-base-100 shadow-lg">
          <div className="card-body">
            {/* Experiment Selection */}
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <FlaskConical className="h-4 w-4 text-experiment-active" />
                <span className="text-sm font-medium">Link to Experiment</span>
              </div>
              <button
                type="button"
                onClick={() => setShowExperimentSelector(!showExperimentSelector)}
                className="btn btn-sm btn-ghost"
              >
                {selectedExperiment ? 'Change' : 'Select'}
              </button>
            </div>

            {showExperimentSelector && (
              <div className="mb-4 p-4 bg-base-50 rounded-lg">
                <div className="form-control">
                  <label className="label">
                    <span className="label-text">Choose an active experiment (optional)</span>
                  </label>
                  <select
                    value={selectedExperimentIds[0] || ''}
                    onChange={(e) => setValue('experimentIds', e.target.value ? [e.target.value] : [])}
                    className="select select-bordered"
                    disabled={isLoading}
                  >
                    <option value="">No experiment</option>
                    {experiments.map((experiment) => (
                      <option key={experiment.id} value={experiment.id}>
                        {experiment.title}
                      </option>
                    ))}
                  </select>
                </div>
                <button
                  type="button"
                  onClick={() => setShowExperimentSelector(false)}
                  className="btn btn-sm btn-ghost mt-2"
                >
                  Done
                </button>
              </div>
            )}

            {selectedExperiment && (
              <div className="alert alert-info mb-4">
                <FlaskConical className="h-4 w-4" />
                <div>
                  <div className="font-medium">Linked to: {selectedExperiment.title}</div>
                  <div className="text-xs opacity-70">{selectedExperiment.description}</div>
                </div>
                <button
                  type="button"
                  onClick={() => setValue('experimentIds', [])}
                  className="btn btn-sm btn-ghost"
                >
                  Remove
                </button>
              </div>
            )}

            {/* Main Content Area */}
            <div className="form-control">
              <label className="label">
                <span className="label-text">What's on your mind?</span>
                <span className="label-text-alt text-base-content/60">
                  {wordCount} words
                </span>
              </label>
              <TextareaAutosize
                {...register('initialMessage')}
                placeholder="Start writing about your day, thoughts, or experiences. The AI will ask follow-up questions to help you reflect deeper..."
                className={`textarea textarea-bordered w-full resize-none ${
                  errors.initialMessage ? 'textarea-error' : 'focus:textarea-primary'
                }`}
                minRows={8}
                maxRows={20}
                disabled={isCreating}
              />
              {errors.initialMessage && (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.initialMessage.message}</span>
                </label>
              )}
            </div>

            {/* Writing Tips */}
            <div className="bg-base-50 rounded-lg p-4 mt-4">
              <div className="flex items-start space-x-2">
                <Sparkles className="h-4 w-4 text-journal-primary mt-0.5 flex-shrink-0" />
                <div className="text-sm">
                  <div className="font-medium text-base-content mb-1">Writing Tips:</div>
                  <ul className="text-base-content/70 space-y-1 text-xs">
                    <li>• Write about specific events, feelings, or observations from your day</li>
                    <li>• Don't worry about perfect grammar - focus on authentic expression</li>
                    <li>• The AI will ask follow-up questions to help you dig deeper</li>
                    <li>• Mention any experiments you're running to track their impact</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <ErrorMessage 
            message={error} 
            onRetry={() => setError(null)}
          />
        )}

        {/* Actions */}
        <div className="flex items-center justify-between">
          <Link href="/dashboard/journal" className="btn btn-ghost">
            Cancel
          </Link>
          
          <div className="flex items-center space-x-3">
            <div className="text-sm text-base-content/60">
              {initialMessage.length > 0 && (
                <span>Ready to start the conversation</span>
              )}
            </div>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={isCreating || !initialMessage.trim()}
            >
              {isCreating ? (
                <LoadingSpinner size="sm" />
              ) : (
                <>
                  <MessageCircle className="h-4 w-4 mr-2" />
                  Start Conversation
                </>
              )}
            </button>
          </div>
        </div>
      </form>
    </div>
  )
}
