// frontend/src/app/dashboard/journal/new/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import TextareaAutosize from 'react-textarea-autosize'
import { 
  BookOpen, 
  Save, 
  ArrowLeft, 
  Sparkles, 
  FlaskConical,
  MessageCircle 
} from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { Experiment } from '@/types'
import { LoadingSpinner } from '@/components/LoadingSpinner'
import { ErrorMessage } from '@/components/ErrorMessage'

const journalEntrySchema = z.object({
  content: z.string()
    .min(10, 'Please write at least 10 characters')
    .max(10000, 'Entry is too long (max 10,000 characters)'),
  experimentId: z.string().optional(),
})

type JournalEntryFormData = z.infer<typeof journalEntrySchema>

export default function NewJournalEntryPage() {
  const [isLoading, setIsLoading] = useState(false)
  const [isCreating, setIsCreating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [experiments, setExperiments] = useState<Experiment[]>([])
  const [showExperimentSelector, setShowExperimentSelector] = useState(false)
  const router = useRouter()

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors },
  } = useForm<JournalEntryFormData>({
    resolver: zodResolver(journalEntrySchema),
    defaultValues: {
      content: '',
      experimentId: '',
    }
  })

  const content = watch('content')
  const selectedExperimentId = watch('experimentId')

  // Load experiments on mount
  useEffect(() => {
    const loadExperiments = async () => {
      try {
        setIsLoading(true)
        const response = await apiClient.getExperiments()
        if (response.success && response.data) {
          // Filter for active experiments
          const now = new Date()
          const activeExperiments = response.data.filter(exp => {
            const startDate = new Date(exp.startDate)
            const endDate = new Date(exp.endDate)
            return now >= startDate && now <= endDate
          })
          setExperiments(activeExperiments)
        }
      } catch (err) {
        console.error('Error loading experiments:', err)
      } finally {
        setIsLoading(false)
      }
    }

    loadExperiments()
  }, [])

  const onSubmit = async (data: JournalEntryFormData) => {
    setIsCreating(true)
    setError(null)

    try {
      const response = await apiClient.createJournalEntry({
        content: data.content,
        experimentId: data.experimentId || undefined,
      })

      if (response.success && response.data) {
        // Redirect to the created entry
        router.push(`/dashboard/journal/${response.data.id}`)
      } else {
        setError(response.error || 'Failed to create journal entry')
      }
    } catch (err) {
      console.error('Error creating journal entry:', err)
      setError('Unable to create journal entry. Please try again.')
    } finally {
      setIsCreating(false)
    }
  }

  const selectedExperiment = experiments.find(exp => exp.id === selectedExperimentId)
  const wordCount = content ? content.trim().split(/\s+/).filter(word => word.length > 0).length : 0

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <Link 
            href="/dashboard/journal" 
            className="btn btn-ghost btn-circle"
            aria-label="Back to journal"
          >
            <ArrowLeft className="h-5 w-5" />
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-base-content flex items-center gap-2">
              <BookOpen className="h-6 w-6 text-journal-primary" />
              New Journal Entry
            </h1>
            <p className="text-base-content/60">Share your thoughts and reflections</p>
          </div>
        </div>
      </div>

      {/* Form */}
      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        <div className="card bg-base-100 shadow-lg">
          <div className="card-body">
            {/* Experiment Selection */}
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-2">
                <FlaskConical className="h-4 w-4 text-experiment-active" />
                <span className="text-sm font-medium">Link to Experiment</span>
              </div>
              <button
                type="button"
                onClick={() => setShowExperimentSelector(!showExperimentSelector)}
                className="btn btn-sm btn-ghost"
              >
                {selectedExperiment ? 'Change' : 'Select'}
              </button>
            </div>

            {showExperimentSelector && (
              <div className="mb-4 p-4 bg-base-50 rounded-lg">
                <div className="form-control">
                  <label className="label">
                    <span className="label-text">Choose an active experiment (optional)</span>
                  </label>
                  <select
                    {...register('experimentId')}
                    className="select select-bordered"
                    disabled={isLoading}
                  >
                    <option value="">No experiment</option>
                    {experiments.map((experiment) => (
                      <option key={experiment.id} value={experiment.id}>
                        {experiment.title}
                      </option>
                    ))}
                  </select>
                </div>
                <button
                  type="button"
                  onClick={() => setShowExperimentSelector(false)}
                  className="btn btn-sm btn-ghost mt-2"
                >
                  Done
                </button>
              </div>
            )}

            {selectedExperiment && (
              <div className="alert alert-info mb-4">
                <FlaskConical className="h-4 w-4" />
                <div>
                  <div className="font-medium">Linked to: {selectedExperiment.title}</div>
                  <div className="text-xs opacity-70">{selectedExperiment.description}</div>
                </div>
                <button
                  type="button"
                  onClick={() => setValue('experimentId', '')}
                  className="btn btn-sm btn-ghost"
                >
                  Remove
                </button>
              </div>
            )}

            {/* Main Content Area */}
            <div className="form-control">
              <label className="label">
                <span className="label-text">What's on your mind?</span>
                <span className="label-text-alt text-base-content/60">
                  {wordCount} words
                </span>
              </label>
              <TextareaAutosize
                {...register('content')}
                placeholder="Start writing about your day, thoughts, or experiences. The AI will ask follow-up questions to help you reflect deeper..."
                className={`textarea textarea-bordered w-full resize-none ${
                  errors.content ? 'textarea-error' : 'focus:textarea-primary'
                }`}
                minRows={8}
                maxRows={20}
                disabled={isCreating}
              />
              {errors.content && (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.content.message}</span>
                </label>
              )}
            </div>

            {/* Writing Tips */}
            <div className="bg-base-50 rounded-lg p-4 mt-4">
              <div className="flex items-start space-x-2">
                <Sparkles className="h-4 w-4 text-journal-primary mt-0.5 flex-shrink-0" />
                <div className="text-sm">
                  <div className="font-medium text-base-content mb-1">Writing Tips:</div>
                  <ul className="text-base-content/70 space-y-1 text-xs">
                    <li>• Write about specific events, feelings, or observations from your day</li>
                    <li>• Don't worry about perfect grammar - focus on authentic expression</li>
                    <li>• The AI will ask follow-up questions to help you dig deeper</li>
                    <li>• Mention any experiments you're running to track their impact</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <ErrorMessage 
            message={error} 
            onRetry={() => setError(null)}
          />
        )}

        {/* Actions */}
        <div className="flex items-center justify-between">
          <Link href="/dashboard/journal" className="btn btn-ghost">
            Cancel
          </Link>
          
          <div className="flex items-center space-x-3">
            <div className="text-sm text-base-content/60">
              {content.length > 0 && (
                <span>Ready to start the conversation</span>
              )}
            </div>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={isCreating || !content.trim()}
            >
              {isCreating ? (
                <LoadingSpinner size="sm" />
              ) : (
                <>
                  <MessageCircle className="h-4 w-4 mr-2" />
                  Start Conversation
                </>
              )}
            </button>
          </div>
        </div>
      </form>
    </div>
  )
}

// frontend/src/routes/journal/new/+page.svelte
<script lang="ts">
  import { ArrowLeft, Save } from 'lucide-svelte';
  import { goto } from '$app/navigation';
  import { journalStore } from '$lib/stores/journal';
  import type { CreateJournalEntryInput } from '$lib/api/client';
  
  let loading = $state(false);
  let error = $state('');
  
  // Form fields
  let title = $state('');
  let content = $state('');
  
  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    
    if (!content.trim()) {
      error = 'Content is required';
      return;
    }
    
    loading = true;
    error = '';
    
    try {
      const entryData: CreateJournalEntryInput = {
        title: title.trim() || undefined,
        content: content.trim()
      };
      
      await journalStore.create(entryData);
      goto('/journal');
    } catch (err) {
      error = 'Failed to create journal entry';
      console.error(err);
    } finally {
      loading = false;
    }
  }
  
  function handleCancel() {
    goto('/journal');
  }
  
  // Auto-save functionality (optional)
  let autoSaveTimer: number | null = null;
  
  function scheduleAutoSave() {
    if (autoSaveTimer) {
      clearTimeout(autoSaveTimer);
    }
    
    // Auto-save after 2 seconds of inactivity
    autoSaveTimer = window.setTimeout(() => {
      if (content.trim()) {
        // Could implement draft saving here
        console.log('Auto-saving draft...');
      }
    }, 2000);
  }
  
  // Schedule auto-save when content changes
  $effect(() => {
    if (content) {
      scheduleAutoSave();
    }
  });
</script>

<svelte:head>
  <title>New Journal Entry - Journal App</title>
</svelte:head>

<div class="container mx-auto px-4 py-8 max-w-4xl">
  <div class="flex items-center gap-4 mb-6">
    <button 
      class="btn btn-ghost btn-sm"
      onclick={handleCancel}
      aria-label="Go back to journal"
    >
      <ArrowLeft size={20} />
    </button>
    <h1 class="text-3xl font-bold">New Journal Entry</h1>
  </div>
  
  {#if error}
    <div class="alert alert-error mb-6">
      <span>{error}</span>
    </div>
  {/if}
  
  <div class="card bg-base-100 shadow-sm">
    <div class="card-body">
      <form onsubmit={handleSubmit}>
        <!-- Title -->
        <div class="form-control mb-4">
          <label class="label" for="title">
            <span class="label-text">Title (optional)</span>
          </label>
          <input 
            id="title"
            type="text"
            class="input input-bordered w-full"
            bind:value={title}
            placeholder="Enter a title for your journal entry"
            disabled={loading}
          />
        </div>
        
        <!-- Content -->
        <div class="form-control mb-6">
          <label class="label" for="content">
            <span class="label-text">Content *</span>
          </label>
          <textarea 
            id="content"
            class="textarea textarea-bordered w-full min-h-96"
            bind:value={content}
            placeholder="What's on your mind? Write about your day, thoughts, feelings, or anything else..."
            required
            disabled={loading}
            rows="20"
          ></textarea>
          <div class="label">
            <span class="label-text-alt">{content.length} characters</span>
            <span class="label-text-alt">Markdown supported</span>
          </div>
        </div>
        
        <!-- Actions -->
        <div class="flex justify-end gap-2">
          <button 
            type="button"
            class="btn btn-ghost"
            onclick={handleCancel}
            disabled={loading}
          >
            Cancel
          </button>
          <button 
            type="submit"
            class="btn btn-primary"
            disabled={loading || !content.trim()}
          >
            {#if loading}
              <span class="loading loading-spinner loading-sm"></span>
            {:else}
              <Save size={16} />
            {/if}
            Save Entry
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

<style>
  .min-h-96 {
    min-height: 24rem;
  }
</style>
