// frontend/src/routes/experiments/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { authStore } from '$lib/stores/auth';
  import { experimentsApi, type ExperimentResponse } from '$lib/api/experiments';
  import { Plus, Beaker, Calendar, BarChart, Trash2, Edit3, Eye } from 'lucide-svelte';

  // Reactive state for experiments data
  let userExperiments: ExperimentResponse[] = $state([]);
  let loading = $state(true);
  let error = $state<string | null>(null);

  // Load data on component mount
  onMount(async () => {
    await loadExperimentsData();
  });

  // Separate function to load experiments data
  async function loadExperimentsData() {
    try {
      loading = true;
      error = null;

      const experimentsData = await experimentsApi.getUserExperiments();
      userExperiments = experimentsData;
    } catch (err) {
      console.error('Failed to load experiments:', err);
      if (err instanceof Error && err.message === 'Authentication required') {
        goto('/login');
        return;
      }
      error = err instanceof Error ? err.message : 'Failed to load experiments';
    } finally {
      loading = false;
    }
  }

  // Helper functions
  function getExperimentStatus(experiment: ExperimentResponse): 'upcoming' | 'active' | 'completed' {
    const today = new Date().toISOString().split('T')[0];
    const startDate = experiment.startDate;
    const endDate = experiment.endDate;

    if (today < startDate) return 'upcoming';
    if (today > endDate) return 'completed';
    return 'active';
  }

  function getExperimentStatusColor(status: 'upcoming' | 'active' | 'completed'): string {
    switch (status) {
      case 'upcoming':
        return 'badge-info';
      case 'active':
        return 'badge-success';
      case 'completed':
        return 'badge-neutral';
    }
  }

  function formatDateRange(startDate: string, endDate: string): string {
    const start = new Date(startDate);
    const end = new Date(endDate);
    const options: Intl.DateTimeFormatOptions = {
      month: 'short',
      day: 'numeric',
    };

    if (start.getFullYear() !== end.getFullYear()) {
      return `${start.toLocaleDateString('en-US', { ...options, year: 'numeric' })} - ${end.toLocaleDateString('en-US', { ...options, year: 'numeric' })}`;
    }

    return `${start.toLocaleDateString('en-US', options)} - ${end.toLocaleDateString('en-US', options)}`;
  }

  function getDuration(startDate: string, endDate: string): number {
    const start = new Date(startDate);
    const end = new Date(endDate);
    return Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)) + 1;
  }

  async function deleteExperiment(id: string) {
    if (!confirm('Are you sure you want to delete this experiment? This action cannot be undone.')) {
      return;
    }

    try {
      await experimentsApi.deleteExperiment(id);
      await loadExperimentsData(); // Reload the list
    } catch (err) {
      console.error('Failed to delete experiment:', err);
      error = err instanceof Error ? err.message : 'Failed to delete experiment';
    }
  }

  // Group experiments by status
  let groupedExperiments = $derived(() => {
    const grouped = {
      active: userExperiments.filter((exp) => getExperimentStatus(exp) === 'active'),
      upcoming: userExperiments.filter((exp) => getExperimentStatus(exp) === 'upcoming'),
      completed: userExperiments.filter((exp) => getExperimentStatus(exp) === 'completed'),
    };
    return grouped;
  });
</script>

<svelte:head>
  <title>Experiments</title>
</svelte:head>

<div class="container mx-auto px-4 py-8">
  <!-- Header -->
  <div class="mb-8 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <Beaker class="text-primary h-8 w-8" />
      <div>
        <h1 class="text-base-content text-3xl font-bold">Experiments</h1>
        <p class="text-base-content/60">Short-lived self-improvement tests to discover what makes your life better</p>
      </div>
    </div>
    <a href="/experiments/create" class="btn btn-primary gap-2">
      <Plus class="h-5 w-5" />
      New Experiment
    </a>
  </div>

  <!-- Loading State -->
  {#if loading}
    <div class="flex items-center justify-center py-12">
      <span class="loading loading-spinner loading-lg text-primary"></span>
    </div>
  {:else if error}
    <!-- Error State -->
    <div class="alert alert-error mb-6">
      <p>{error}</p>
      <button onclick={loadExperimentsData} class="btn btn-ghost btn-sm"> Try again </button>
    </div>
  {:else if userExperiments.length === 0}
    <!-- Empty State -->
    <div class="py-12 text-center">
      <Beaker class="text-base-content/30 mx-auto mb-4 h-16 w-16" />
      <h3 class="text-base-content mb-2 text-xl font-semibold">No experiments yet</h3>
      <p class="text-base-content/60 mx-auto mb-6 max-w-md">
        Start your first experiment to test changes in your life and track what makes you happier and more productive.
      </p>
      <a href="/experiments/create" class="btn btn-primary gap-2">
        <Plus class="h-5 w-5" />
        Create Your First Experiment
      </a>
    </div>
  {:else}
    <!-- Experiments List -->
    <div class="space-y-8">
      <!-- Active Experiments -->
      {#if groupedExperiments().active.length > 0}
        <div>
          <h2 class="text-base-content mb-4 flex items-center gap-2 text-xl font-semibold">
            <span class="bg-success h-3 w-3 rounded-full"></span>
            Active Experiments ({groupedExperiments().active.length})
          </h2>
          <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {#each groupedExperiments().active as experiment}
              <div class="card bg-base-100 shadow-lg transition-shadow hover:shadow-xl">
                <div class="card-body">
                  <div class="flex items-start justify-between">
                    <div class="flex-1">
                      <h3 class="card-title text-base-content">{experiment.title}</h3>
                      {#if experiment.description}
                        <p class="text-base-content/60 mb-3 line-clamp-2 text-sm">{experiment.description}</p>
                      {/if}
                    </div>
                    <span class="badge {getExperimentStatusColor(getExperimentStatus(experiment))}">
                      {getExperimentStatus(experiment)}
                    </span>
                  </div>

                  <div class="text-base-content/60 mb-4 flex items-center gap-4 text-sm">
                    <div class="flex items-center gap-1">
                      <Calendar class="h-4 w-4" />
                      {formatDateRange(experiment.startDate, experiment.endDate)}
                    </div>
                    <div class="flex items-center gap-1">
                      <BarChart class="h-4 w-4" />
                      {getDuration(experiment.startDate, experiment.endDate)} days
                    </div>
                  </div>

                  <div class="card-actions justify-end">
                    <a href="/experiments/{experiment.id}/dashboard" class="btn btn-primary btn-sm gap-1">
                      <BarChart class="h-4 w-4" />
                      Dashboard
                    </a>
                    <a href="/experiments/{experiment.id}" class="btn btn-ghost btn-sm btn-circle" title="View Details">
                      <Eye class="h-4 w-4" />
                    </a>
                    <a href="/experiments/{experiment.id}/edit" class="btn btn-ghost btn-sm btn-circle" title="Edit">
                      <Edit3 class="h-4 w-4" />
                    </a>
                    <button onclick={() => deleteExperiment(experiment.id)} class="btn btn-ghost btn-sm btn-circle text-error hover:bg-error/10" title="Delete">
                      <Trash2 class="h-4 w-4" />
                    </button>
                  </div>
                </div>
              </div>
            {/each}
          </div>
        </div>
      {/if}

      <!-- Upcoming Experiments -->
      {#if groupedExperiments().upcoming.length > 0}
        <div>
          <h2 class="text-base-content mb-4 flex items-center gap-2 text-xl font-semibold">
            <span class="bg-info h-3 w-3 rounded-full"></span>
            Upcoming Experiments ({groupedExperiments().upcoming.length})
          </h2>
          <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {#each groupedExperiments().upcoming as experiment}
              <div class="card bg-base-100 shadow-lg transition-shadow hover:shadow-xl">
                <div class="card-body">
                  <div class="flex items-start justify-between">
                    <div class="flex-1">
                      <h3 class="card-title text-base-content">{experiment.title}</h3>
                      {#if experiment.description}
                        <p class="text-base-content/60 mb-3 line-clamp-2 text-sm">{experiment.description}</p>
                      {/if}
                    </div>
                    <span class="badge {getExperimentStatusColor(getExperimentStatus(experiment))}">
                      {getExperimentStatus(experiment)}
                    </span>
                  </div>

                  <div class="text-base-content/60 mb-4 flex items-center gap-4 text-sm">
                    <div class="flex items-center gap-1">
                      <Calendar class="h-4 w-4" />
                      {formatDateRange(experiment.startDate, experiment.endDate)}
                    </div>
                    <div class="flex items-center gap-1">
                      <BarChart class="h-4 w-4" />
                      {getDuration(experiment.startDate, experiment.endDate)} days
                    </div>
                  </div>

                  <div class="card-actions justify-end">
                    <a href="/experiments/{experiment.id}" class="btn btn-secondary btn-sm gap-1">
                      <Eye class="h-4 w-4" />
                      View Details
                    </a>
                    <a href="/experiments/{experiment.id}/edit" class="btn btn-ghost btn-sm btn-circle" title="Edit">
                      <Edit3 class="h-4 w-4" />
                    </a>
                    <button onclick={() => deleteExperiment(experiment.id)} class="btn btn-ghost btn-sm btn-circle text-error hover:bg-error/10" title="Delete">
                      <Trash2 class="h-4 w-4" />
                    </button>
                  </div>
                </div>
              </div>
            {/each}
          </div>
        </div>
      {/if}

      <!-- Completed Experiments -->
      {#if groupedExperiments().completed.length > 0}
        <div>
          <h2 class="text-base-content mb-4 flex items-center gap-2 text-xl font-semibold">
            <span class="bg-neutral h-3 w-3 rounded-full"></span>
            Completed Experiments ({groupedExperiments().completed.length})
          </h2>
          <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {#each groupedExperiments().completed as experiment}
              <div class="card bg-base-100 opacity-75 shadow-lg transition-shadow hover:shadow-xl">
                <div class="card-body">
                  <div class="flex items-start justify-between">
                    <div class="flex-1">
                      <h3 class="card-title text-base-content">{experiment.title}</h3>
                      {#if experiment.description}
                        <p class="text-base-content/60 mb-3 line-clamp-2 text-sm">{experiment.description}</p>
                      {/if}
                    </div>
                    <span class="badge {getExperimentStatusColor(getExperimentStatus(experiment))}">
                      {getExperimentStatus(experiment)}
                    </span>
                  </div>

                  <div class="text-base-content/60 mb-4 flex items-center gap-4 text-sm">
                    <div class="flex items-center gap-1">
                      <Calendar class="h-4 w-4" />
                      {formatDateRange(experiment.startDate, experiment.endDate)}
                    </div>
                    <div class="flex items-center gap-1">
                      <BarChart class="h-4 w-4" />
                      {getDuration(experiment.startDate, experiment.endDate)} days
                    </div>
                  </div>

                  <div class="card-actions justify-end">
                    <a href="/experiments/{experiment.id}/dashboard" class="btn btn-primary btn-sm gap-1">
                      <BarChart class="h-4 w-4" />
                      View Results
                    </a>
                    <a href="/experiments/{experiment.id}" class="btn btn-ghost btn-sm btn-circle" title="View Details">
                      <Eye class="h-4 w-4" />
                    </a>
                    <button onclick={() => deleteExperiment(experiment.id)} class="btn btn-ghost btn-sm btn-circle text-error hover:bg-error/10" title="Delete">
                      <Trash2 class="h-4 w-4" />
                    </button>
                  </div>
                </div>
              </div>
            {/each}
          </div>
        </div>
      {/if}
    </div>
  {/if}
</div>

<style>
  .line-clamp-2 {
    overflow: hidden;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
    line-clamp: 2;
  }
</style>

// frontend/src/app/dashboard/experiments/page.tsx
'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { 
  FlaskConical, 
  Plus, 
  Calendar, 
  Target, 
  CheckCircle, 
  Clock,
  TrendingUp,
  BookOpen
} from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { Experiment } from '@/types'
import { LoadingSpinner } from '@/components/LoadingSpinner'
import { ErrorMessage } from '@/components/ErrorMessage'
import { dateUtils, cn } from '@/utils'

export default function ExperimentsPage() {
  const [experiments, setExperiments] = useState<Experiment[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [filter, setFilter] = useState<'all' | 'active' | 'completed' | 'upcoming'>('all')

  useEffect(() => {
    const loadExperiments = async () => {
      try {
        setIsLoading(true)
        setError(null)
        
        const response = await apiClient.getExperiments()
        if (response.success && response.data) {
          setExperiments(response.data)
        } else {
          setError(response.error || 'Failed to load experiments')
        }
      } catch (err) {
        console.error('Error loading experiments:', err)
        setError('Unable to load experiments')
      } finally {
        setIsLoading(false)
      }
    }

    loadExperiments()
  }, [])

  // Categorize experiments by status
  const categorizeExperiment = (experiment: Experiment) => {
    const now = new Date()
    const startDate = new Date(experiment.startDate)
    const endDate = new Date(experiment.endDate)
    
    if (now < startDate) return 'upcoming'
    if (now > endDate) return 'completed'
    return 'active'
  }

  const filteredExperiments = experiments.filter(experiment => {
    if (filter === 'all') return true
    return categorizeExperiment(experiment) === filter
  })

  const getStatusInfo = (experiment: Experiment) => {
    const status = categorizeExperiment(experiment)
    const now = new Date()
    const startDate = new Date(experiment.startDate)
    const endDate = new Date(experiment.endDate)
    
    switch (status) {
      case 'upcoming':
        return {
          status: 'upcoming',
          label: 'Upcoming',
          color: 'text-warning',
          bgColor: 'bg-warning/10',
          icon: Clock,
          description: `Starts ${dateUtils.getRelativeTime(startDate)}`
        }
      case 'active':
        const totalDays = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24))
        const daysElapsed = Math.ceil((now.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24))
        const progress = Math.min((daysElapsed / totalDays) * 100, 100)
        
        return {
          status: 'active',
          label: 'Active',
          color: 'text-success',
          bgColor: 'bg-success/10',
          icon: Target,
          description: `Day ${daysElapsed} of ${totalDays}`,
          progress
        }
      case 'completed':
        return {
          status: 'completed',
          label: 'Completed',
          color: 'text-base-content/60',
          bgColor: 'bg-base-200',
          icon: CheckCircle,
          description: `Ended ${dateUtils.getRelativeTime(endDate)}`
        }
      default:
        return {
          status: 'unknown',
          label: 'Unknown',
          color: 'text-base-content/60',
          bgColor: 'bg-base-200',
          icon: FlaskConical,
          description: ''
        }
    }
  }

  const statusCounts = {
    all: experiments.length,
    active: experiments.filter(exp => categorizeExperiment(exp) === 'active').length,
    upcoming: experiments.filter(exp => categorizeExperiment(exp) === 'upcoming').length,
    completed: experiments.filter(exp => categorizeExperiment(exp) === 'completed').length,
  }

  if (isLoading) {
    return <LoadingSpinner size="lg" />
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-base-content flex items-center gap-2">
            <FlaskConical className="h-6 w-6 text-experiment-active" />
            Self-Experiments
          </h1>
          <p className="text-base-content/60 mt-1">
            Track your lifestyle experiments and measure their impact
          </p>
        </div>
        
        <Link href="/dashboard/experiments/new" className="btn btn-primary">
          <Plus className="h-4 w-4 mr-2" />
          New Experiment
        </Link>
      </div>

      {/* Filter Tabs */}
      <div className="card bg-base-100 shadow-sm">
        <div className="card-body">
          <div className="tabs tabs-boxed">
            {[
              { key: 'all', label: 'All', count: statusCounts.all },
              { key: 'active', label: 'Active', count: statusCounts.active },
              { key: 'upcoming', label: 'Upcoming', count: statusCounts.upcoming },
              { key: 'completed', label: 'Completed', count: statusCounts.completed },
            ].map((tab) => (
              <button
                key={tab.key}
                onClick={() => setFilter(tab.key as any)}
                className={cn(
                  'tab gap-2',
                  filter === tab.key && 'tab-active'
                )}
              >
                {tab.label}
                <div className="badge badge-sm">{tab.count}</div>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Error Message */}
      {error && (
        <ErrorMessage 
          message={error} 
          onRetry={() => window.location.reload()}
        />
      )}

      {/* Experiments List */}
      {filteredExperiments.length === 0 ? (
        <div className="card bg-base-100 shadow-sm">
          <div className="card-body text-center py-12">
            <FlaskConical className="h-16 w-16 text-base-content/20 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-base-content mb-2">
              {filter === 'all' 
                ? 'No experiments yet'
                : `No ${filter} experiments`
              }
            </h3>
            <p className="text-base-content/60 mb-4">
              {filter === 'all' 
                ? 'Create your first experiment to start tracking lifestyle changes.'
                : `You don't have any ${filter} experiments at the moment.`
              }
            </p>
            <Link href="/dashboard/experiments/new" className="btn btn-primary">
              <Plus className="h-4 w-4 mr-2" />
              Create Experiment
            </Link>
          </div>
        </div>
      ) : (
        <div className="grid gap-4">
          {filteredExperiments.map((experiment) => {
            const statusInfo = getStatusInfo(experiment)
            const StatusIcon = statusInfo.icon

            return (
              <Link
                key={experiment.id}
                href={`/dashboard/experiments/${experiment.id}`}
                className="card bg-base-100 shadow-sm hover:shadow-md transition-shadow"
              >
                <div className="card-body">
                  {/* Header */}
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold text-base-content line-clamp-1">
                        {experiment.title}
                      </h3>
                      <p className="text-sm text-base-content/70 mt-1 line-clamp-2">
                        {experiment.description}
                      </p>
                    </div>
                    <div className={cn(
                      'flex items-center px-2 py-1 rounded-full text-xs font-medium ml-4',
                      statusInfo.bgColor,
                      statusInfo.color
                    )}>
                      <StatusIcon className="h-3 w-3 mr-1" />
                      {statusInfo.label}
                    </div>
                  </div>

                  {/* Progress Bar for Active Experiments */}
                  {statusInfo.status === 'active' && statusInfo.progress !== undefined && (
                    <div className="mb-3">
                      <div className="flex items-center justify-between text-xs text-base-content/60 mb-1">
                        <span>Progress</span>
                        <span>{Math.round(statusInfo.progress)}%</span>
                      </div>
                      <div className="w-full bg-base-200 rounded-full h-2">
                        <div 
                          className="bg-experiment-active h-2 rounded-full transition-all duration-300"
                          style={{ width: `${statusInfo.progress}%` }}
                        ></div>
                      </div>
                    </div>
                  )}

                  {/* Daily Task */}
                  <div className="bg-base-50 rounded-lg p-3 mb-3">
                    <div className="flex items-start space-x-2">
                      <Target className="h-4 w-4 text-experiment-active mt-0.5 flex-shrink-0" />
                      <div className="flex-1">
                        <div className="text-sm font-medium text-base-content mb-1">
                          Daily Task
                        </div>
                        <div className="text-xs text-base-content/70">
                          {experiment.dailyTaskDescription}
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Footer */}
                  <div className="flex items-center justify-between text-xs text-base-content/60">
                    <div className="flex items-center space-x-4">
                      <div className="flex items-center">
                        <Calendar className="h-3 w-3 mr-1" />
                        {dateUtils.formatDate(experiment.startDate)} - {dateUtils.formatDate(experiment.endDate)}
                      </div>
                    </div>
                    
                    <div className="flex items-center space-x-3">
                      <div className="flex items-center">
                        <BookOpen className="h-3 w-3 mr-1" />
                        View Journal Entries
                      </div>
                      <div className="flex items-center">
                        <TrendingUp className="h-3 w-3 mr-1" />
                        {statusInfo.description}
                      </div>
                    </div>
                  </div>
                </div>
              </Link>
            )
          })}
        </div>
      )}
    </div>
  )
}
