// src/routes/experiments/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Target, Plus, Calendar, AlertCircle } from 'lucide-svelte';
	import type { Experiment } from '$lib/types';
	
	let experiments = $state<Experiment[]>([]);
	let loading = $state(true);
	let page = $state(1);
	let hasMore = $state(true);
	let activeExperimentsOnly = $state(false);
	
	onMount(async () => {
		await loadExperiments();
	});
	
	async function loadExperiments(reset = false) {
		try {
			loading = true;
			const currentPage = reset ? 1 : page;
			const activeParam = activeExperimentsOnly ? 'true' : '';
			
			const response = await fetch(`/api/experiments?page=${currentPage}&limit=10${activeParam ? `&active=${activeParam}` : ''}`);
			
			if (response.ok) {
				const data = await response.json();
				if (reset) {
					experiments = data.experiments;
				} else {
					experiments = [...experiments, ...data.experiments];
				}
				hasMore = data.experiments.length === 10;
				page = currentPage + 1;
			}
		} catch (error) {
			console.error('Error loading experiments:', error);
		} finally {
			loading = false;
		}
	}
	
	function toggleActiveFilter() {
		activeExperimentsOnly = !activeExperimentsOnly;
		loadExperiments(true);
	}
	
	function formatDate(date: string | Date) {
		const dateObj = typeof date === 'string' ? new Date(date) : date;
		return dateObj.toLocaleDateString('en-US', {
			year: 'numeric',
			month: 'short',
			day: 'numeric'
		});
	}
	
	function calculateProgress(startDate: string | Date, endDate: string | Date) {
		const start = typeof startDate === 'string' ? new Date(startDate) : startDate;
		const end = typeof endDate === 'string' ? new Date(endDate) : endDate;
		const now = new Date();
		
		// If the experiment hasn't started yet
		if (now < start) return 0;
		
		// If the experiment is already over
		if (now > end) return 100;
		
		// Calculate progress
		const total = end.getTime() - start.getTime();
		const current = now.getTime() - start.getTime();
		return Math.round((current / total) * 100);
	}
	
	function getExperimentStatus(experiment: Experiment) {
		const now = new Date();
		const start = new Date(experiment.startDate);
		const end = new Date(experiment.endDate);
		
		if (!experiment.isActive) return 'Inactive';
		if (now < start) return 'Upcoming';
		if (now > end) return 'Completed';
		return 'Active';
	}
</script>

<svelte:head>
	<title>Experiments - Journal App</title>
</svelte:head>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex items-center justify-between">
		<div>
			<h1 class="text-3xl font-bold text-base-content">Experiments</h1>
			<p class="text-base-content/70 mt-1">Track your personal quests and research</p>
		</div>
		<a href="/experiments/new" class="btn btn-primary gap-2">
			<Plus size={20} />
			New Experiment
		</a>
	</div>
	
	<!-- Filters -->
	<div class="flex flex-wrap gap-2">
		<button 
			class="btn btn-sm {activeExperimentsOnly ? 'btn-secondary' : 'btn-outline'}" 
			onclick={toggleActiveFilter}
		>
			{activeExperimentsOnly ? 'Showing Active Only' : 'Show All Experiments'}
		</button>
	</div>

	<!-- Experiments List -->
	{#if loading && experiments.length === 0}
		<div class="flex justify-center py-12">
			<span class="loading loading-spinner loading-lg"></span>
		</div>
	{:else if experiments.length === 0}
		<div class="text-center py-16">
			<Target size={64} class="mx-auto text-base-content/30 mb-4" />
			<h2 class="text-xl font-semibold mb-2">No experiments yet</h2>
			<p class="text-base-content/70 mb-6">Start a new personal experiment to track and measure your growth</p>
			<a href="/experiments/new" class="btn btn-primary gap-2">
				<Plus size={20} />
				Create First Experiment
			</a>
		</div>
	{:else}
		<div class="space-y-4">
			{#each experiments as experiment}
				{@const status = getExperimentStatus(experiment)}
				{@const progress = calculateProgress(experiment.startDate, experiment.endDate)}
				
				<div class="card bg-base-100 border border-base-300 hover:border-base-400 transition-colors">
					<div class="card-body">
						<div class="flex items-start justify-between">
							<div class="flex-1">
								<a href="/experiments/{experiment.id}" class="hover:underline">
									<h3 class="font-semibold text-lg">{experiment.title}</h3>
								</a>
								
								{#if experiment.description}
									<p class="text-base-content/70 mt-1 line-clamp-2">{experiment.description}</p>
								{/if}
								
								<div class="flex flex-wrap gap-3 items-center mt-3">
									<div class="flex items-center gap-1 text-sm text-base-content/60">
										<Calendar size={16} />
										<span>{formatDate(experiment.startDate)} - {formatDate(experiment.endDate)}</span>
									</div>
									
									<div class="badge {status === 'Active' ? 'badge-success' : 
									            status === 'Upcoming' ? 'badge-info' : 
												status === 'Completed' ? 'badge-neutral' : 
												'badge-ghost'}">
										{status}
									</div>
								</div>
								
								{#if status === 'Active'}
									<div class="mt-4">
										<div class="flex justify-between text-xs mb-1">
											<span>Progress</span>
											<span>{progress}%</span>
										</div>
										<progress class="progress progress-success w-full" value={progress} max="100"></progress>
									</div>
								{/if}
							</div>
							
							<a href="/experiments/{experiment.id}" class="btn btn-ghost btn-sm btn-circle">
								<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
								</svg>
							</a>
						</div>
					</div>
				</div>
			{/each}
			
			{#if hasMore}
				<div class="flex justify-center pt-4">
					<button class="btn btn-outline" onclick={() => loadExperiments()} disabled={loading}>
						{#if loading}
							<span class="loading loading-spinner loading-sm"></span>
						{:else}
							Load More
						{/if}
					</button>
				</div>
			{/if}
		</div>
	{/if}
</div>

// frontend/src/app/dashboard/experiments/page.tsx
'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { 
  FlaskConical, 
  Plus, 
  Calendar, 
  Target, 
  CheckCircle, 
  Clock,
  TrendingUp,
  BookOpen
} from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { Experiment } from '@/types'
import { LoadingSpinner } from '@/components/LoadingSpinner'
import { ErrorMessage } from '@/components/ErrorMessage'
import { dateUtils, cn } from '@/utils'

export default function ExperimentsPage() {
  const [experiments, setExperiments] = useState<Experiment[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [filter, setFilter] = useState<'all' | 'active' | 'completed' | 'upcoming'>('all')

  useEffect(() => {
    const loadExperiments = async () => {
      try {
        setIsLoading(true)
        setError(null)
        
        const response = await apiClient.getExperiments()
        if (response.success && response.data) {
          setExperiments(response.data)
        } else {
          setError(response.error || 'Failed to load experiments')
        }
      } catch (err) {
        console.error('Error loading experiments:', err)
        setError('Unable to load experiments')
      } finally {
        setIsLoading(false)
      }
    }

    loadExperiments()
  }, [])

  // Categorize experiments by status
  const categorizeExperiment = (experiment: Experiment) => {
    const now = new Date()
    const startDate = new Date(experiment.startDate)
    const endDate = new Date(experiment.endDate)
    
    if (now < startDate) return 'upcoming'
    if (now > endDate) return 'completed'
    return 'active'
  }

  const filteredExperiments = experiments.filter(experiment => {
    if (filter === 'all') return true
    return categorizeExperiment(experiment) === filter
  })

  const getStatusInfo = (experiment: Experiment) => {
    const status = categorizeExperiment(experiment)
    const now = new Date()
    const startDate = new Date(experiment.startDate)
    const endDate = new Date(experiment.endDate)
    
    switch (status) {
      case 'upcoming':
        return {
          status: 'upcoming',
          label: 'Upcoming',
          color: 'text-warning',
          bgColor: 'bg-warning/10',
          icon: Clock,
          description: `Starts ${dateUtils.getRelativeTime(startDate)}`
        }
      case 'active':
        const totalDays = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24))
        const daysElapsed = Math.ceil((now.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24))
        const progress = Math.min((daysElapsed / totalDays) * 100, 100)
        
        return {
          status: 'active',
          label: 'Active',
          color: 'text-success',
          bgColor: 'bg-success/10',
          icon: Target,
          description: `Day ${daysElapsed} of ${totalDays}`,
          progress
        }
      case 'completed':
        return {
          status: 'completed',
          label: 'Completed',
          color: 'text-base-content/60',
          bgColor: 'bg-base-200',
          icon: CheckCircle,
          description: `Ended ${dateUtils.getRelativeTime(endDate)}`
        }
      default:
        return {
          status: 'unknown',
          label: 'Unknown',
          color: 'text-base-content/60',
          bgColor: 'bg-base-200',
          icon: FlaskConical,
          description: ''
        }
    }
  }

  const statusCounts = {
    all: experiments.length,
    active: experiments.filter(exp => categorizeExperiment(exp) === 'active').length,
    upcoming: experiments.filter(exp => categorizeExperiment(exp) === 'upcoming').length,
    completed: experiments.filter(exp => categorizeExperiment(exp) === 'completed').length,
  }

  if (isLoading) {
    return <LoadingSpinner size="lg" />
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-base-content flex items-center gap-2">
            <FlaskConical className="h-6 w-6 text-experiment-active" />
            Self-Experiments
          </h1>
          <p className="text-base-content/60 mt-1">
            Track your lifestyle experiments and measure their impact
          </p>
        </div>
        
        <Link href="/dashboard/experiments/new" className="btn btn-primary">
          <Plus className="h-4 w-4 mr-2" />
          New Experiment
        </Link>
      </div>

      {/* Filter Tabs */}
      <div className="card bg-base-100 shadow-sm">
        <div className="card-body">
          <div className="tabs tabs-boxed">
            {[
              { key: 'all', label: 'All', count: statusCounts.all },
              { key: 'active', label: 'Active', count: statusCounts.active },
              { key: 'upcoming', label: 'Upcoming', count: statusCounts.upcoming },
              { key: 'completed', label: 'Completed', count: statusCounts.completed },
            ].map((tab) => (
              <button
                key={tab.key}
                onClick={() => setFilter(tab.key as any)}
                className={cn(
                  'tab gap-2',
                  filter === tab.key && 'tab-active'
                )}
              >
                {tab.label}
                <div className="badge badge-sm">{tab.count}</div>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Error Message */}
      {error && (
        <ErrorMessage 
          message={error} 
          onRetry={() => window.location.reload()}
        />
      )}

      {/* Experiments List */}
      {filteredExperiments.length === 0 ? (
        <div className="card bg-base-100 shadow-sm">
          <div className="card-body text-center py-12">
            <FlaskConical className="h-16 w-16 text-base-content/20 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-base-content mb-2">
              {filter === 'all' 
                ? 'No experiments yet'
                : `No ${filter} experiments`
              }
            </h3>
            <p className="text-base-content/60 mb-4">
              {filter === 'all' 
                ? 'Create your first experiment to start tracking lifestyle changes.'
                : `You don't have any ${filter} experiments at the moment.`
              }
            </p>
            <Link href="/dashboard/experiments/new" className="btn btn-primary">
              <Plus className="h-4 w-4 mr-2" />
              Create Experiment
            </Link>
          </div>
        </div>
      ) : (
        <div className="grid gap-4">
          {filteredExperiments.map((experiment) => {
            const statusInfo = getStatusInfo(experiment)
            const StatusIcon = statusInfo.icon

            return (
              <Link
                key={experiment.id}
                href={`/dashboard/experiments/${experiment.id}`}
                className="card bg-base-100 shadow-sm hover:shadow-md transition-shadow"
              >
                <div className="card-body">
                  {/* Header */}
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold text-base-content line-clamp-1">
                        {experiment.title}
                      </h3>
                      <p className="text-sm text-base-content/70 mt-1 line-clamp-2">
                        {experiment.description}
                      </p>
                    </div>
                    <div className={cn(
                      'flex items-center px-2 py-1 rounded-full text-xs font-medium ml-4',
                      statusInfo.bgColor,
                      statusInfo.color
                    )}>
                      <StatusIcon className="h-3 w-3 mr-1" />
                      {statusInfo.label}
                    </div>
                  </div>

                  {/* Progress Bar for Active Experiments */}
                  {statusInfo.status === 'active' && statusInfo.progress !== undefined && (
                    <div className="mb-3">
                      <div className="flex items-center justify-between text-xs text-base-content/60 mb-1">
                        <span>Progress</span>
                        <span>{Math.round(statusInfo.progress)}%</span>
                      </div>
                      <div className="w-full bg-base-200 rounded-full h-2">
                        <div 
                          className="bg-experiment-active h-2 rounded-full transition-all duration-300"
                          style={{ width: `${statusInfo.progress}%` }}
                        ></div>
                      </div>
                    </div>
                  )}

                  {/* Daily Task */}
                  <div className="bg-base-50 rounded-lg p-3 mb-3">
                    <div className="flex items-start space-x-2">
                      <Target className="h-4 w-4 text-experiment-active mt-0.5 flex-shrink-0" />
                      <div className="flex-1">
                        <div className="text-sm font-medium text-base-content mb-1">
                          Daily Task
                        </div>
                        <div className="text-xs text-base-content/70">
                          {experiment.dailyTaskDescription}
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Footer */}
                  <div className="flex items-center justify-between text-xs text-base-content/60">
                    <div className="flex items-center space-x-4">
                      <div className="flex items-center">
                        <Calendar className="h-3 w-3 mr-1" />
                        {dateUtils.formatDate(experiment.startDate)} - {dateUtils.formatDate(experiment.endDate)}
                      </div>
                    </div>
                    
                    <div className="flex items-center space-x-3">
                      <div className="flex items-center">
                        <BookOpen className="h-3 w-3 mr-1" />
                        View Journal Entries
                      </div>
                      <div className="flex items-center">
                        <TrendingUp className="h-3 w-3 mr-1" />
                        {statusInfo.description}
                      </div>
                    </div>
                  </div>
                </div>
              </Link>
            )
          })}
        </div>
      )}
    </div>
  )
}
