// frontend/src/app/dashboard/page.tsx
'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { 
  BookOpen, 
  FlaskConical, 
  TrendingUp, 
  Plus, 
  Calendar,
  BarChart3,
  Target
} from 'lucide-react'
import { auth } from '@/lib/auth'
import { apiClient } from '@/lib/api-client'
import { JournalEntry, Experiment, CharacterStat } from '@/types'
import { LoadingSpinner } from '@/components/LoadingSpinner'
import { ErrorMessage } from '@/components/ErrorMessage'
import { dateUtils, textUtils } from '@/utils'

export default function DashboardPage() {
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [recentEntries, setRecentEntries] = useState<JournalEntry[]>([])
  const [activeExperiments, setActiveExperiments] = useState<Experiment[]>([])
  const [characterStats, setCharacterStats] = useState<CharacterStat[]>([])
  
  const user = auth.getUser()

  useEffect(() => {
    const loadDashboardData = async () => {
      try {
        setIsLoading(true)
        setError(null)

        // Load recent journal entries
        const journalResponse = await apiClient.getJournalEntries()
        if (journalResponse.success && journalResponse.data) {
          // Get the 3 most recent entries
          const sorted = journalResponse.data.sort((a, b) => 
            new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
          )
          setRecentEntries(sorted.slice(0, 3))
        }

        // Load active experiments
        const experimentsResponse = await apiClient.getExperiments()
        if (experimentsResponse.success && experimentsResponse.data) {
          // Filter for active experiments (current date is between start and end date)
          const now = new Date()
          const active = experimentsResponse.data.filter(exp => {
            const startDate = new Date(exp.startDate)
            const endDate = new Date(exp.endDate)
            return now >= startDate && now <= endDate
          })
          setActiveExperiments(active)
        }

        // Load character stats
        const statsResponse = await apiClient.getCharacterStats()
        if (statsResponse.success && statsResponse.data) {
          setCharacterStats(statsResponse.data.slice(0, 4)) // Show top 4 stats
        }

      } catch (err) {
        console.error('Dashboard loading error:', err)
        setError('Failed to load dashboard data')
      } finally {
        setIsLoading(false)
      }
    }

    loadDashboardData()
  }, [])

  if (isLoading) {
    return <LoadingSpinner size="lg" />
  }

  if (error) {
    return (
      <div className="flex justify-center">
        <ErrorMessage 
          message={error} 
          onRetry={() => window.location.reload()}
        />
      </div>
    )
  }

  return (
    <div className="spacing-responsive-y">
      {/* Welcome Header */}
      <div className="bg-gradient-to-r from-primary to-secondary rounded-xl sm:rounded-2xl p-4 sm:p-6 text-primary-content animate-fade-in">
        <h1 className="text-xl sm:text-2xl md:text-3xl font-bold mb-2">
          Welcome back, {user?.username}! 👋
        </h1>
        <p className="text-base sm:text-lg opacity-90">
          Ready to continue your growth journey? Here's what's happening today.
        </p>
      </div>

      {/* Quick Actions */}
      <div className="grid-responsive-2-4">
        <Link href="/dashboard/journal/new" className="btn btn-primary btn-sm sm:btn-md lg:btn-lg flex-col h-16 sm:h-20">
          <BookOpen className="h-4 w-4 sm:h-6 sm:w-6 mb-1" />
          <span className="text-xs sm:text-sm">New Entry</span>
        </Link>
        <Link href="/dashboard/experiments/new" className="btn btn-outline btn-sm sm:btn-md lg:btn-lg flex-col h-16 sm:h-20">
          <FlaskConical className="h-4 w-4 sm:h-6 sm:w-6 mb-1" />
          <span className="text-xs sm:text-sm">New Experiment</span>
        </Link>
        <Link href="/dashboard/character-stats" className="btn btn-outline btn-sm sm:btn-md lg:btn-lg flex-col h-16 sm:h-20">
          <TrendingUp className="h-4 w-4 sm:h-6 sm:w-6 mb-1" />
          <span className="text-xs sm:text-sm">View Stats</span>
        </Link>
        <Link href="/dashboard/journal" className="btn btn-outline btn-sm sm:btn-md lg:btn-lg flex-col h-16 sm:h-20">
          <BarChart3 className="h-4 w-4 sm:h-6 sm:w-6 mb-1" />
          <span className="text-xs sm:text-sm">All Entries</span>
        </Link>
      </div>

      {/* Main Content Grid */}
      <div className="grid-responsive-1-2">
        {/* Recent Journal Entries */}
        <div className="card bg-base-100 shadow-lg animate-slide-up">
          <div className="card-body p-4 sm:p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="card-title text-base sm:text-lg">
                <BookOpen className="h-4 w-4 sm:h-5 sm:w-5 text-primary" />
                Recent Journal Entries
              </h2>
              <Link href="/dashboard/journal" className="btn btn-sm btn-ghost">
                View All
              </Link>
            </div>
            
            {recentEntries.length === 0 ? (
              <div className="text-center py-6 sm:py-8">
                <BookOpen className="h-10 w-10 sm:h-12 sm:w-12 text-base-content/20 mx-auto mb-4" />
                <p className="text-base-content/60 mb-4 text-sm sm:text-base">No journal entries yet</p>
                <Link href="/dashboard/journal/new" className="btn btn-primary btn-sm">
                  Write Your First Entry
                </Link>
              </div>
            ) : (
              <div className="space-y-3 sm:space-y-4">
                {recentEntries.map((entry) => (
                  <Link
                    key={entry.id}
                    href={`/dashboard/journal/${entry.id}`}
                    className="block p-3 sm:p-4 border border-base-200 rounded-lg hover:bg-base-50 transition-colors animate-fade-in"
                  >
                    <div className="flex items-start justify-between mb-2">
                      <h3 className="font-medium text-base-content line-clamp-1 text-sm sm:text-base">
                        {entry.title || 'Untitled Entry'}
                      </h3>
                      <span className="text-xs text-base-content/60 whitespace-nowrap ml-2">
                        {dateUtils.getRelativeTime(entry.createdAt)}
                      </span>
                    </div>
                    <p className="text-xs sm:text-sm text-base-content/70 line-clamp-2">
                      {entry.content ? textUtils.truncate(entry.content, 100) : 'No content'}
                    </p>
                  </Link>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Active Experiments */}
        <div className="card bg-base-100 shadow-lg animate-slide-up">
          <div className="card-body p-4 sm:p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="card-title text-base sm:text-lg">
                <FlaskConical className="h-4 w-4 sm:h-5 sm:w-5 text-secondary" />
                Active Experiments
              </h2>
              <Link href="/dashboard/experiments" className="btn btn-sm btn-ghost">
                View All
              </Link>
            </div>
            
            {activeExperiments.length === 0 ? (
              <div className="text-center py-6 sm:py-8">
                <FlaskConical className="h-10 w-10 sm:h-12 sm:w-12 text-base-content/20 mx-auto mb-4" />
                <p className="text-base-content/60 mb-4 text-sm sm:text-base">No active experiments</p>
                <Link href="/dashboard/experiments/new" className="btn btn-primary btn-sm">
                  Start Your First Experiment
                </Link>
              </div>
            ) : (
              <div className="space-y-3 sm:space-y-4">
                {activeExperiments.map((experiment) => (
                  <Link
                    key={experiment.id}
                    href={`/dashboard/experiments/${experiment.id}`}
                    className="block p-3 sm:p-4 border border-base-200 rounded-lg hover:bg-base-50 transition-colors animate-fade-in"
                  >
                    <div className="flex items-start justify-between mb-2">
                      <h3 className="font-medium text-base-content line-clamp-1 text-sm sm:text-base">
                        {experiment.title}
                      </h3>
                      <div className="flex items-center text-xs text-accent ml-2">
                        <Target className="h-3 w-3 mr-1" />
                        Active
                      </div>
                    </div>
                    <p className="text-xs sm:text-sm text-base-content/70 line-clamp-1 mb-2">
                      {experiment.description}
                    </p>
                    <div className="flex items-center text-xs text-base-content/60">
                      <Calendar className="h-3 w-3 mr-1" />
                      <span className="truncate">
                        {dateUtils.formatDate(experiment.startDate)} - {dateUtils.formatDate(experiment.endDate)}
                      </span>
                    </div>
                  </Link>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Character Stats Overview */}
      <div className="card bg-base-100 shadow-lg animate-slide-up">
        <div className="card-body p-4 sm:p-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="card-title text-base sm:text-lg">
              <TrendingUp className="h-4 w-4 sm:h-5 sm:w-5 text-accent" />
              Character Stats Progress
            </h2>
            <Link href="/dashboard/character-stats" className="btn btn-sm btn-ghost">
              View All Stats
            </Link>
          </div>
          
          {characterStats.length === 0 ? (
            <div className="text-center py-6 sm:py-8">
              <TrendingUp className="h-10 w-10 sm:h-12 sm:w-12 text-base-content/20 mx-auto mb-4" />
              <p className="text-base-content/60 mb-4 text-sm sm:text-base">No character stats created yet</p>
              <Link href="/dashboard/character-stats/new" className="btn btn-primary btn-sm">
                Create Your First Stat
              </Link>
            </div>
          ) : (
            <div className="grid sm:grid-cols-2 gap-4 sm:gap-6">
              {characterStats.map((stat) => (
                <div key={stat.id} className="space-y-2 animate-fade-in">
                  <div className="flex items-center justify-between">
                    <span className="font-medium text-base-content text-sm sm:text-base">{stat.name}</span>
                    <span className="text-xs sm:text-sm text-base-content/60">{stat.currentXp} XP</span>
                  </div>
                  <div className="w-full bg-base-200 rounded-full h-2">
                    <div 
                      className="bg-gradient-to-r from-primary to-secondary h-2 rounded-full transition-all duration-300"
                      style={{ width: `${Math.min((stat.currentXp / 1000) * 100, 100)}%` }}
                    ></div>
                  </div>
                  <p className="text-xs text-base-content/60 line-clamp-1">
                    {stat.description}
                  </p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// frontend/src/routes/experiments/[id]/dashboard/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { experimentsApi } from '$lib/api/experiments';
  import type { ExperimentDashboardResponse } from '$lib/api/experiments';
  import { ArrowLeft, Calendar, BarChart, Target, Award, TrendingUp, CheckCircle2, Clock, Book, Star } from 'lucide-svelte';

  // Reactive state
  let dashboard: ExperimentDashboardResponse | null = $state(null);
  let loading = $state(true);
  let error = $state<string | null>(null);

  // Get experiment ID from URL
  let experimentId = $derived($page.params.id);

  // Load data on component mount
  onMount(async () => {
    await loadDashboard();
  });

  async function loadDashboard() {
    try {
      loading = true;
      error = null;

      dashboard = await experimentsApi.getExperimentDashboard(experimentId);
    } catch (err) {
      console.error('Failed to load experiment dashboard:', err);
      if (err instanceof Error && err.message === 'Authentication required') {
        goto('/login');
        return;
      }
      error = err instanceof Error ? err.message : 'Failed to load experiment dashboard';
    } finally {
      loading = false;
    }
  }

  // Helper functions
  function getExperimentStatus(exp: ExperimentDashboardResponse['experiment']): 'upcoming' | 'active' | 'completed' {
    const today = new Date().toISOString().split('T')[0];
    const startDate = exp.startDate;
    const endDate = exp.endDate;

    if (today < startDate) return 'upcoming';
    if (today > endDate) return 'completed';
    return 'active';
  }

  function getExperimentStatusColor(status: 'upcoming' | 'active' | 'completed'): string {
    switch (status) {
      case 'upcoming':
        return 'badge-primary';
      case 'active':
        return 'badge-success';
      case 'completed':
        return 'badge-neutral';
      default:
        return 'badge-neutral';
    }
  }

  function formatDateRange(startDate: string, endDate: string): string {
    const start = new Date(startDate);
    const end = new Date(endDate);

    return `${start.toLocaleDateString()} - ${end.toLocaleDateString()}`;
  }

  function formatDate(dateString: string): string {
    return new Date(dateString).toLocaleDateString();
  }

  function getProgressPercentage(current: number, total: number): number {
    if (total === 0) return 0;
    return Math.round((current / total) * 100);
  }

  function getTaskCompletionRate(task: ExperimentDashboardResponse['tasks'][0]): number {
    if (!dashboard) return 0;
    const totalPossible = dashboard.stats.totalDays;
    return totalPossible > 0 ? Math.round((task.completionCount / totalPossible) * 100) : 0;
  }
</script>

<svelte:head>
  <title>{dashboard ? `${dashboard.experiment.title} Dashboard` : 'Experiment Dashboard'} - Journal App</title>
</svelte:head>

<div class="container mx-auto max-w-6xl px-4 py-8">
  <!-- Navigation -->
  <div class="mb-6">
    <a href="/experiments/{experimentId}" class="text-base-content/60 hover:text-base-content inline-flex items-center gap-2 transition-colors">
      <ArrowLeft class="h-4 w-4" />
      Back to Experiment
    </a>
  </div>

  <!-- Loading State -->
  {#if loading}
    <div class="flex items-center justify-center py-12">
      <div class="border-primary h-8 w-8 animate-spin rounded-full border-b-2"></div>
    </div>
  {:else if error}
    <!-- Error State -->
    <div class="alert alert-error">
      <h3 class="mb-2 text-lg font-semibold">Error Loading Dashboard</h3>
      <p class="mb-4">{error}</p>
      <button onclick={loadDashboard} class="btn btn-outline btn-error"> Try Again </button>
    </div>
  {:else if dashboard}
    <!-- Dashboard Content -->
    <div class="space-y-8">
      <!-- Header -->
      <div class="card from-primary/10 to-secondary/10 border-primary/20 border bg-gradient-to-br">
        <div class="card-body">
          <div class="flex items-start justify-between">
            <div class="flex-1">
              <div class="mb-2 flex items-center gap-3">
                <h1 class="text-base-content text-3xl font-bold">{dashboard.experiment.title}</h1>
                <span class="badge {getExperimentStatusColor(getExperimentStatus(dashboard.experiment))} badge-lg">
                  {getExperimentStatus(dashboard.experiment)}
                </span>
              </div>

              {#if dashboard.experiment.description}
                <p class="text-base-content/70 mb-4 text-lg">{dashboard.experiment.description}</p>
              {/if}

              <div class="text-base-content/60 flex flex-wrap items-center gap-6 text-sm">
                <div class="flex items-center gap-2">
                  <Calendar class="h-4 w-4" />
                  <span>{formatDateRange(dashboard.experiment.startDate, dashboard.experiment.endDate)}</span>
                </div>
                <div class="flex items-center gap-2">
                  <BarChart class="h-4 w-4" />
                  <span>{dashboard.stats.totalDays} days</span>
                </div>
                <div class="flex items-center gap-2">
                  <TrendingUp class="h-4 w-4" />
                  <span>{dashboard.stats.completionPercentage}% complete</span>
                </div>
              </div>
            </div>

            <!-- Progress Circle -->
            <div class="flex-shrink-0">
              <div class="radial-progress text-primary" style="--value:{dashboard.stats.completionPercentage};" role="progressbar">
                {dashboard.stats.completionPercentage}%
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Key Stats Grid -->
      <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
        <div class="card bg-base-100 border-base-300 border">
          <div class="card-body text-center">
            <div class="text-primary text-3xl font-bold">{dashboard.stats.daysCompleted}</div>
            <div class="text-base-content/60 text-sm">Days Completed</div>
            <div class="text-base-content/40 text-xs">out of {dashboard.stats.totalDays}</div>
          </div>
        </div>

        <div class="card bg-base-100 border-base-300 border">
          <div class="card-body text-center">
            <div class="text-secondary text-3xl font-bold">{dashboard.stats.tasksCompleted}</div>
            <div class="text-base-content/60 text-sm">Tasks Completed</div>
            <div class="text-base-content/40 text-xs">out of {dashboard.stats.totalTaskInstances}</div>
          </div>
        </div>

        <div class="card bg-base-100 border-base-300 border">
          <div class="card-body text-center">
            <div class="text-accent text-3xl font-bold">{dashboard.stats.totalXpEarned}</div>
            <div class="text-base-content/60 text-sm">Total XP Earned</div>
            <div class="text-base-content/40 text-xs">{dashboard.xpBreakdown.fromTasks} from tasks, {dashboard.xpBreakdown.fromJournals} from journals</div>
          </div>
        </div>

        <div class="card bg-base-100 border-base-300 border">
          <div class="card-body text-center">
            <div class="text-warning text-3xl font-bold">{dashboard.journalEntries.length}</div>
            <div class="text-base-content/60 text-sm">Journal Entries</div>
            <div class="text-base-content/40 text-xs">during experiment</div>
          </div>
        </div>
      </div>

      <!-- Content Grid -->
      <div class="grid grid-cols-1 gap-8 lg:grid-cols-2">
        <!-- Tasks Progress -->
        <div class="card bg-base-100 border-base-300 border">
          <div class="card-body">
            <h2 class="text-base-content mb-6 flex items-center gap-2 text-2xl font-bold">
              <Target class="text-primary h-6 w-6" />
              Task Progress
            </h2>

            {#if dashboard.tasks.length > 0}
              <div class="space-y-6">
                {#each dashboard.tasks as task}
                  <div class="space-y-3">
                    <div class="flex items-start justify-between">
                      <div class="flex-1">
                        <h3 class="text-base-content font-semibold">{task.description}</h3>
                        <div class="text-base-content/60 mt-1 flex items-center gap-4 text-sm">
                          <div class="flex items-center gap-1">
                            <CheckCircle2 class="h-4 w-4" />
                            <span>{task.completionCount} completions</span>
                          </div>
                          {#if task.xpReward && task.xpReward > 0}
                            <div class="flex items-center gap-1">
                              <Award class="h-4 w-4" />
                              <span>{task.completionCount * task.xpReward} XP earned</span>
                            </div>
                          {/if}
                        </div>
                      </div>
                      <div class="text-right">
                        <div class="text-primary text-lg font-bold">{getTaskCompletionRate(task)}%</div>
                        <div class="text-base-content/40 text-xs">completion rate</div>
                      </div>
                    </div>
                    <!-- Progress Bar -->
                    <div class="bg-base-300 h-2 w-full rounded-full">
                      <div class="bg-primary h-2 rounded-full transition-all duration-300" style="width: {getTaskCompletionRate(task)}%"></div>
                    </div>

                    <!-- Recent Completions -->
                    {#if task.completions.length > 0}
                      <div class="text-base-content/40 text-xs">
                        <span>Recent: </span>
                        {#each task.completions.slice(0, 5) as completion, i}
                          <span class="inline-block">
                            {formatDate(completion.completedDate)}{i < task.completions.slice(0, 5).length - 1 ? ', ' : ''}
                          </span>
                        {/each}
                        {#if task.completions.length > 5}
                          <span>and {task.completions.length - 5} more...</span>
                        {/if}
                      </div>
                    {/if}
                  </div>
                {/each}
              </div>
            {:else}
              <div class="py-8 text-center">
                <Target class="text-base-content/30 mx-auto mb-4 h-12 w-12" />
                <h3 class="text-base-content mb-2 text-lg font-medium">No tasks defined</h3>
                <p class="text-base-content/60">Add some daily tasks to track progress.</p>
              </div>
            {/if}
          </div>
        </div>

        <!-- Journal Entries -->
        <div class="card bg-base-100 border-base-300 border">
          <div class="card-body">
            <h2 class="text-base-content mb-6 flex items-center gap-2 text-2xl font-bold">
              <Book class="text-secondary h-6 w-6" />
              Journal Entries
            </h2>

            {#if dashboard.journalEntries.length > 0}
              <div class="space-y-4">
                {#each dashboard.journalEntries as entry}
                  <div class="card bg-base-200 border-base-300 border">
                    <div class="card-body p-4">
                      <div class="flex items-start justify-between">
                        <div class="flex-1">
                          <h3 class="text-base-content mb-1 font-semibold">{entry.title}</h3>
                          {#if entry.synopsis}
                            <p class="text-base-content/60 mb-2 line-clamp-2 text-sm">{entry.synopsis}</p>
                          {/if}
                          <div class="text-base-content/40 text-xs">
                            {formatDate(entry.createdAt)}
                          </div>
                        </div>
                        <a href="/journal/{entry.id}" class="btn btn-ghost btn-sm" title="View entry"> View </a>
                      </div>
                    </div>
                  </div>
                {/each}
              </div>

              {#if dashboard.journalEntries.length > 5}
                <div class="mt-4 text-center">
                  <a href="/journal" class="btn btn-outline btn-sm"> View All Journal Entries </a>
                </div>
              {/if}
            {:else}
              <div class="py-8 text-center">
                <Book class="text-base-content/30 mx-auto mb-4 h-12 w-12" />
                <h3 class="text-base-content mb-2 text-lg font-medium">No journal entries</h3>
                <p class="text-base-content/60 mb-4">Write about your experiment experience to track insights and progress.</p>
                <a href="/journal/create" class="btn btn-secondary btn-sm">
                  <Book class="h-4 w-4" />
                  Start Journaling
                </a>
              </div>
            {/if}
          </div>
        </div>
      </div>

      <!-- XP Breakdown -->
      <div class="card bg-base-100 border-base-300 border">
        <div class="card-body">
          <h2 class="text-base-content mb-6 flex items-center gap-2 text-2xl font-bold">
            <Star class="text-warning h-6 w-6" />
            XP Breakdown
          </h2>

          <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
            <div class="text-center">
              <div class="text-primary mb-2 text-3xl font-bold">{dashboard.xpBreakdown.fromTasks}</div>
              <div class="text-base-content/60 mb-1 text-sm">From Tasks</div>
              <div class="text-base-content/40 text-xs">
                {getProgressPercentage(dashboard.xpBreakdown.fromTasks, dashboard.xpBreakdown.total)}% of total
              </div>
            </div>

            <div class="text-center">
              <div class="text-secondary mb-2 text-3xl font-bold">{dashboard.xpBreakdown.fromJournals}</div>
              <div class="text-base-content/60 mb-1 text-sm">From Journals</div>
              <div class="text-base-content/40 text-xs">
                {getProgressPercentage(dashboard.xpBreakdown.fromJournals, dashboard.xpBreakdown.total)}% of total
              </div>
            </div>

            <div class="text-center">
              <div class="text-accent mb-2 text-3xl font-bold">{dashboard.xpBreakdown.total}</div>
              <div class="text-base-content/60 mb-1 text-sm">Total XP</div>
              <div class="text-base-content/40 text-xs">Overall experiment earnings</div>
            </div>
          </div>

          <!-- Visual XP Breakdown -->
          {#if dashboard.xpBreakdown.total > 0}
            <div class="mt-6">
              <div class="flex h-4 overflow-hidden rounded-lg">
                <div class="bg-primary" style="width: {getProgressPercentage(dashboard.xpBreakdown.fromTasks, dashboard.xpBreakdown.total)}%"></div>
                <div class="bg-secondary" style="width: {getProgressPercentage(dashboard.xpBreakdown.fromJournals, dashboard.xpBreakdown.total)}%"></div>
              </div>
              <div class="text-base-content/40 mt-2 flex justify-between text-xs">
                <span>Tasks</span>
                <span>Journals</span>
              </div>
            </div>
          {/if}
        </div>
      </div>
    </div>
  {:else}
    <!-- Not found state -->
    <div class="py-12 text-center">
      <h2 class="text-base-content mb-2 text-2xl font-bold">Experiment Not Found</h2>
      <p class="text-base-content/60 mb-6">The experiment dashboard you're looking for doesn't exist or you don't have access to it.</p>
      <a href="/experiments" class="btn btn-primary"> Back to Experiments </a>
    </div>
  {/if}
</div>
