// frontend/src/components/LoadingSpinner.tsx
'use client'

import { LoadingSpinnerProps } from '@/types'
import { cn } from '@/utils'

export function LoadingSpinner({ size = 'md', className }: LoadingSpinnerProps) {
  const sizeClasses = {
    sm: 'loading-sm',
    md: 'loading-md',
    lg: 'loading-lg'
  }

  return (
    <div className={cn('flex justify-center items-center p-4', className)}>
      <span className={cn('loading loading-spinner', sizeClasses[size])}></span>
    </div>
  )
}

export default LoadingSpinner

// frontend/src/lib/components/LoadingSpinner.svelte
<script lang="ts">
  interface Props {
    size?: 'sm' | 'md' | 'lg';
    class?: string;
  }
  
  let { size = 'md', class: className = '' }: Props = $props();
  
  const sizeClasses = {
    sm: 'loading-sm',
    md: 'loading-md',
    lg: 'loading-lg'
  };
</script>

<span class="loading loading-spinner {sizeClasses[size]} {className}"></span>
