// frontend/src/routes/auth/register/+page.svelte
<script lang="ts">
	import { auth } from '$lib/auth.js';
	import { goto } from '$app/navigation';
	import LoadingSpinner from '$lib/components/LoadingSpinner.svelte';
	import Alert from '$lib/components/Alert.svelte';

	let name = $state('');
	let email = $state('');
	let password = $state('');
	let confirmPassword = $state('');
	let timezone = $state(Intl.DateTimeFormat().resolvedOptions().timeZone);
	let isLoading = $state(false);
	let error = $state('');

	async function handleRegister(event: Event) {
		event.preventDefault();
		
		if (!name || !email || !password || !confirmPassword) {
			error = 'Please fill in all fields';
			return;
		}

		if (password !== confirmPassword) {
			error = 'Passwords do not match';
			return;
		}

		if (password.length < 6) {
			error = 'Password must be at least 6 characters long';
			return;
		}

		isLoading = true;
		error = '';

		try {
			await auth.register(email, password, name, timezone);
			goto('/');
		} catch (err) {
			error = err instanceof Error ? err.message : 'Registration failed';
		} finally {
			isLoading = false;
		}
	}

	function clearError() {
		error = '';
	}
</script>

<svelte:head>
	<title>Register - Journal</title>
</svelte:head>

<div class="card bg-base-100 shadow-xl animate-fade-in">
	<div class="card-body">
		<h1 class="card-title text-2xl mb-6 justify-center">Create Account</h1>
		
		{#if error}
			<Alert message={error} type="error" onDismiss={clearError} class="mb-4" />
		{/if}

		<form onsubmit={handleRegister} class="space-y-4">
			<div class="form-control">
				<label class="label" for="name">
					<span class="label-text">Full Name</span>
				</label>
				<input
					id="name"
					type="text"
					bind:value={name}
					class="input input-bordered focus-ring"
					placeholder="Enter your full name"
					required
					disabled={isLoading}
				/>
			</div>

			<div class="form-control">
				<label class="label" for="email">
					<span class="label-text">Email</span>
				</label>
				<input
					id="email"
					type="email"
					bind:value={email}
					class="input input-bordered focus-ring"
					placeholder="Enter your email"
					required
					disabled={isLoading}
				/>
			</div>

			<div class="form-control">
				<label class="label" for="password">
					<span class="label-text">Password</span>
				</label>
				<input
					id="password"
					type="password"
					bind:value={password}
					class="input input-bordered focus-ring"
					placeholder="Create a password"
					required
					disabled={isLoading}
					minlength="6"
				/>
				<div class="label">
					<span class="label-text-alt">At least 6 characters</span>
				</div>
			</div>

			<div class="form-control">
				<label class="label" for="confirmPassword">
					<span class="label-text">Confirm Password</span>
				</label>
				<input
					id="confirmPassword"
					type="password"
					bind:value={confirmPassword}
					class="input input-bordered focus-ring"
					placeholder="Confirm your password"
					required
					disabled={isLoading}
				/>
			</div>

			<div class="form-control">
				<label class="label" for="timezone">
					<span class="label-text">Timezone</span>
				</label>
				<input
					id="timezone"
					type="text"
					bind:value={timezone}
					class="input input-bordered focus-ring"
					placeholder="Your timezone"
					disabled={isLoading}
				/>
				<div class="label">
					<span class="label-text-alt">Used for scheduling and timestamps</span>
				</div>
			</div>

			<div class="form-control mt-6">
				<button 
					type="submit" 
					class="btn btn-primary"
					disabled={isLoading || !name || !email || !password || !confirmPassword}
				>
					{#if isLoading}
						<LoadingSpinner size="sm" />
						Creating Account...
					{:else}
						Create Account
					{/if}
				</button>
			</div>
		</form>

		<div class="divider">OR</div>

		<div class="text-center">
			<p class="text-base-content/70">Already have an account?</p>
			<a href="/auth/login" class="link link-primary font-medium">
				Sign in here
			</a>
		</div>
	</div>
</div>

// frontend/src/app/auth/register/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { BookOpen, Eye, EyeOff, Mail, Lock, User } from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { auth } from '@/lib/auth'
import { LoadingSpinner } from '@/components/LoadingSpinner'
import { ErrorMessage } from '@/components/ErrorMessage'

const registerSchema = z.object({
  username: z.string()
    .min(3, 'Username must be at least 3 characters')
    .max(50, 'Username must be less than 50 characters')
    .regex(/^[a-zA-Z0-9_-]+$/, 'Username can only contain letters, numbers, underscores, and hyphens'),
  email: z.string().email('Please enter a valid email address'),
  password: z.string()
    .min(8, 'Password must be at least 8 characters')
    .regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/, 'Password must contain at least one uppercase letter, one lowercase letter, and one number'),
  confirmPassword: z.string(),
}).refine((data) => data.password === data.confirmPassword, {
  message: "Passwords don't match",
  path: ["confirmPassword"],
})

type RegisterFormData = z.infer<typeof registerSchema>

export default function RegisterPage() {
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const router = useRouter()

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterFormData>({
    resolver: zodResolver(registerSchema),
  })

  const onSubmit = async (data: RegisterFormData) => {
    setIsLoading(true)
    setError(null)

    try {
      const { confirmPassword, ...registerData } = data
      const response = await apiClient.register(registerData)
      
      if (response.success && response.data) {
        auth.login(response.data.user, response.data.token)
        apiClient.setAuthToken(response.data.token)
        router.push('/dashboard')
      } else {
        setError(response.error || 'Registration failed')
      }
    } catch (err) {
      setError('Unable to connect to the server. Please try again.')
      console.error('Registration error:', err)
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-base-100 to-base-200 flex items-center justify-center p-4">
      <div className="card w-full max-w-md bg-base-100 shadow-xl">
        <div className="card-body">
          {/* Header */}
          <div className="text-center mb-6">
            <div className="flex items-center justify-center space-x-2 mb-4">
              <BookOpen className="h-8 w-8 text-brand-500" />
              <span className="text-2xl font-bold">Journal</span>
            </div>
            <h1 className="text-xl font-semibold text-base-content">Create Your Account</h1>
            <p className="text-base-content/60">Start your personal growth journey today</p>
          </div>

          {/* Error Message */}
          {error && (
            <ErrorMessage 
              message={error} 
              onRetry={() => setError(null)}
              className="mb-4"
            />
          )}

          {/* Registration Form */}
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            {/* Username Field */}
            <div className="form-control">
              <label className="label">
                <span className="label-text">Username</span>
              </label>
              <div className="relative">
                <input
                  {...register('username')}
                  type="text"
                  placeholder="Choose a username"
                  className={`input input-bordered w-full pl-10 ${errors.username ? 'input-error' : ''}`}
                  disabled={isLoading}
                />
                <User className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-base-content/40" />
              </div>
              {errors.username && (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.username.message}</span>
                </label>
              )}
            </div>

            {/* Email Field */}
            <div className="form-control">
              <label className="label">
                <span className="label-text">Email</span>
              </label>
              <div className="relative">
                <input
                  {...register('email')}
                  type="email"
                  placeholder="Enter your email"
                  className={`input input-bordered w-full pl-10 ${errors.email ? 'input-error' : ''}`}
                  disabled={isLoading}
                />
                <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-base-content/40" />
              </div>
              {errors.email && (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.email.message}</span>
                </label>
              )}
            </div>

            {/* Password Field */}
            <div className="form-control">
              <label className="label">
                <span className="label-text">Password</span>
              </label>
              <div className="relative">
                <input
                  {...register('password')}
                  type={showPassword ? 'text' : 'password'}
                  placeholder="Create a password"
                  className={`input input-bordered w-full pl-10 pr-10 ${errors.password ? 'input-error' : ''}`}
                  disabled={isLoading}
                />
                <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-base-content/40" />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-3 top-1/2 transform -translate-y-1/2 text-base-content/40 hover:text-base-content"
                  disabled={isLoading}
                >
                  {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
              {errors.password && (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.password.message}</span>
                </label>
              )}
            </div>

            {/* Confirm Password Field */}
            <div className="form-control">
              <label className="label">
                <span className="label-text">Confirm Password</span>
              </label>
              <div className="relative">
                <input
                  {...register('confirmPassword')}
                  type={showConfirmPassword ? 'text' : 'password'}
                  placeholder="Confirm your password"
                  className={`input input-bordered w-full pl-10 pr-10 ${errors.confirmPassword ? 'input-error' : ''}`}
                  disabled={isLoading}
                />
                <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-base-content/40" />
                <button
                  type="button"
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                  className="absolute right-3 top-1/2 transform -translate-y-1/2 text-base-content/40 hover:text-base-content"
                  disabled={isLoading}
                >
                  {showConfirmPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </div>
              {errors.confirmPassword && (
                <label className="label">
                  <span className="label-text-alt text-error">{errors.confirmPassword.message}</span>
                </label>
              )}
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              className="btn btn-primary w-full"
              disabled={isLoading}
            >
              {isLoading ? <LoadingSpinner size="sm" /> : 'Create Account'}
            </button>
          </form>

          {/* Footer Links */}
          <div className="divider">or</div>
          
          <div className="text-center space-y-2">
            <p className="text-base-content/60">
              Already have an account?{' '}
              <Link href="/auth/login" className="link link-primary">
                Sign in
              </Link>
            </p>
            <Link href="/" className="link link-neutral text-sm">
              ← Back to homepage
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
